import type { AppLanguage } from '../../../common/contexts/LanguageContext';

export type LocalizedFaqItem = {
  id: number;
  category: string;
  question: string;
  answer: string;
};

export type LocalizedSection = {
  title: string;
  icon: string;
  content: string;
};

const HELP_TERM_REPLACEMENTS: Record<Exclude<AppLanguage, 'en'>, Array<[RegExp, string]>> = {
  hi: [
    [/terms\s*&\s*conditions/gi, 'नियम और शर्तें'],
    [/privacy policy/gi, 'प्राइवेसी पॉलिसी'],
    [/institute profile/gi, 'संस्थान प्रोफाइल'],
    [/institute details/gi, 'संस्थान विवरण'],
    [/institute setup/gi, 'संस्थान सेटअप'],
    [/institute/gi, 'संस्थान'],
    [/dashboard/gi, 'डैशबोर्ड'],
    [/home screen/gi, 'होम स्क्रीन'],
    [/quick links/gi, 'क्विक लिंक्स'],
    [/new batch/gi, 'नया बैच'],
    [/add batch/gi, 'बैच जोड़ें'],
    [/batch schedules screen/gi, 'बैच शेड्यूल स्क्रीन'],
    [/batch menu/gi, 'बैच मेन्यू'],
    [/all students/gi, 'सभी छात्र'],
    [/view students/gi, 'छात्र देखें'],
    [/add new student/gi, 'नया छात्र जोड़ें'],
    [/add student/gi, 'छात्र जोड़ें'],
    [/mark attendance/gi, 'मार्क अटेंडेंस'],
    [/today'?s sessions/gi, 'आज के सेशंस'],
    [/transaction history/gi, 'गतिविधि इतिहास'],
    [/transactions screen/gi, 'गतिविधि स्क्रीन'],
    [/wallet\s*&\s*credits/gi, 'खाता व सारांश'],
    [/mobile number/gi, 'मोबाइल नंबर'],
    [/country code/gi, 'देश कोड'],
    [/profile photo/gi, 'प्रोफाइल फोटो'],
    [/quick contact/gi, 'त्वरित संपर्क'],
    [/resend timer/gi, 'रीसेंड टाइमर'],
    [/resend otp/gi, 'ओटीपी दोबारा भेजें'],
    [/change/gi, 'बदलें'],
    [/continue/gi, 'जारी रखें'],
    [/linked/gi, 'जुड़ा हुआ'],
    [/stat cards/gi, 'सांख्यिकी कार्ड'],
    [/card/gi, 'कार्ड'],
    [/view all/gi, 'सभी देखें'],
    [/calendar/gi, 'कैलेंडर'],
    [/search box/gi, 'खोज बॉक्स'],
    [/clear/gi, 'हटाएं'],
    [/subject/gi, 'विषय'],
    [/guardian name/gi, 'अभिभावक का नाम'],
    [/gender/gi, 'लिंग'],
    [/type/gi, 'प्रकार'],
    [/time/gi, 'समय'],
    [/future/gi, 'आगामी'],
    [/records/gi, 'रिकॉर्ड'],
    [/class entries/gi, 'कक्षा प्रविष्टियां'],
    [/class slot/gi, 'कक्षा स्लॉट'],
    [/date range/gi, 'तिथि सीमा'],
    [/date/gi, 'तारीख'],
    [/confirmation/gi, 'पुष्टिकरण'],
    [/current flow/gi, 'वर्तमान प्रक्रिया'],
    [/submit(?:ted|ting|sion)?/gi, 'सबमिट'],
    [/save(?:d)?/gi, 'सेव'],
    [/editable fields/gi, 'संपादन योग्य फ़ील्ड'],
    [/image area/gi, 'चित्र क्षेत्र'],
    [/tap/gi, 'टैप'],
    [/gallery/gi, 'गैलरी'],
    [/organization/gi, 'संस्थान'],
    [/branding assets/gi, 'ब्रांडिंग सामग्री'],
    [/sign out/gi, 'साइन आउट'],
    [/secure servers/gi, 'सुरक्षित सर्वर'],
    [/cached data/gi, 'कैश किया गया डेटा'],
    [/available credits/gi, 'सारांश'],
    [/total batches/gi, 'कुल बैच'],
    [/total students/gi, 'कुल छात्र'],
    [/attendance today/gi, 'आज की उपस्थिति'],
    [/payment failed/gi, 'पूरा नहीं हो सका'],
    [/verification failed/gi, 'सत्यापन में समस्या'],
    [/registered/gi, 'पंजीकृत'],
    [/existing/gi, 'मौजूदा'],
    [/custom amount/gi, 'कस्टम राशि'],
    [/order summary/gi, 'सारांश'],
    [/refresh/gi, 'रीफ्रेश'],
    [/network/gi, 'नेटवर्क'],
    [/internet/gi, 'इंटरनेट'],
    [/online/gi, 'ऑनलाइन'],
    [/offline/gi, 'ऑफलाइन'],
    [/settings/gi, 'सेटिंग्स'],
    [/profile/gi, 'प्रोफाइल'],
    [/wallet/gi, 'खाता'],
    [/credits/gi, 'मात्रा'],
    [/credit/gi, 'मात्रा'],
    [/transactions/gi, 'गतिविधि'],
    [/transaction/gi, 'गतिविधि'],
    [/login/gi, 'लॉगिन'],
    [/logout/gi, 'लॉगआउट'],
    [/support/gi, 'सपोर्ट'],
    [/admin/gi, 'एडमिन'],
    [/summary/gi, 'सारांश'],
    [/option/gi, 'विकल्प'],
    [/batches/gi, 'बैच'],
    [/batch/gi, 'बैच'],
    [/students/gi, 'छात्र'],
    [/student/gi, 'छात्र'],
    [/schedules/gi, 'शेड्यूल'],
    [/schedule/gi, 'शेड्यूल'],
    [/sessions/gi, 'सेशंस'],
    [/session/gi, 'सेशन'],
    [/service/gi, 'सेवा'],
    [/data/gi, 'डेटा'],
    [/app/gi, 'ऐप'],
    [/flow/gi, 'फ्लो'],
  ],
  bn: [
    [/terms\s*&\s*conditions/gi, 'শর্তাবলী'],
    [/privacy policy/gi, 'প্রাইভেসি পলিসি'],
    [/institute profile/gi, 'ইনস্টিটিউট প্রোফাইল'],
    [/institute details/gi, 'ইনস্টিটিউটের তথ্য'],
    [/institute setup/gi, 'ইনস্টিটিউট সেটআপ'],
    [/institute/gi, 'ইনস্টিটিউট'],
    [/dashboard/gi, 'ড্যাশবোর্ড'],
    [/home screen/gi, 'হোম স্ক্রিন'],
    [/quick links/gi, 'কুইক লিংকস'],
    [/new batch/gi, 'নতুন ব্যাচ'],
    [/add batch/gi, 'ব্যাচ যোগ করুন'],
    [/batch schedules screen/gi, 'ব্যাচ সময়সূচির স্ক্রিন'],
    [/batch menu/gi, 'ব্যাচ মেনু'],
    [/all students/gi, 'সব শিক্ষার্থী'],
    [/view students/gi, 'শিক্ষার্থী দেখুন'],
    [/add new student/gi, 'নতুন শিক্ষার্থী যোগ করুন'],
    [/add student/gi, 'শিক্ষার্থী যোগ করুন'],
    [/mark attendance/gi, 'মার্ক অ্যাটেনডেন্স'],
    [/today'?s sessions/gi, 'আজকের সেশনসমূহ'],
    [/transaction history/gi, 'কার্যকলাপের ইতিহাস'],
    [/transactions screen/gi, 'কার্যকলাপ স্ক্রিন'],
    [/wallet\s*&\s*credits/gi, 'অ্যাকাউন্ট ও সারাংশ'],
    [/mobile number/gi, 'মোবাইল নম্বর'],
    [/country code/gi, 'দেশ কোড'],
    [/profile photo/gi, 'প্রোফাইল ছবি'],
    [/quick contact/gi, 'দ্রুত যোগাযোগ'],
    [/resend timer/gi, 'রিসেন্ড টাইমার'],
    [/resend otp/gi, 'আবার ওটিপি পাঠান'],
    [/change/gi, 'পরিবর্তন করুন'],
    [/continue/gi, 'চালিয়ে যান'],
    [/linked/gi, 'সংযুক্ত'],
    [/stat cards/gi, 'পরিসংখ্যান কার্ড'],
    [/card/gi, 'কার্ড'],
    [/view all/gi, 'সব দেখুন'],
    [/calendar/gi, 'ক্যালেন্ডার'],
    [/search box/gi, 'খোঁজার ঘর'],
    [/clear/gi, 'মুছুন'],
    [/subject/gi, 'বিষয়'],
    [/guardian name/gi, 'অভিভাবকের নাম'],
    [/gender/gi, 'লিঙ্গ'],
    [/type/gi, 'ধরন'],
    [/time/gi, 'সময়'],
    [/future/gi, 'ভবিষ্যৎ'],
    [/records/gi, 'রেকর্ড'],
    [/class entries/gi, 'ক্লাস এন্ট্রি'],
    [/class slot/gi, 'ক্লাস স্লট'],
    [/date range/gi, 'তারিখের সীমা'],
    [/date/gi, 'তারিখ'],
    [/confirmation/gi, 'নিশ্চিতকরণ'],
    [/current flow/gi, 'বর্তমান ধারা'],
    [/submit(?:ted|ting|sion)?/gi, 'সাবমিট'],
    [/save(?:d)?/gi, 'সেভ'],
    [/editable fields/gi, 'সম্পাদনাযোগ্য ঘর'],
    [/image area/gi, 'ছবির স্থান'],
    [/tap/gi, 'ট্যাপ'],
    [/gallery/gi, 'গ্যালারি'],
    [/organization/gi, 'প্রতিষ্ঠান'],
    [/branding assets/gi, 'ব্র্যান্ডিং উপকরণ'],
    [/sign out/gi, 'সাইন আউট'],
    [/secure servers/gi, 'নিরাপদ সার্ভার'],
    [/cached data/gi, 'ক্যাশ করা ডেটা'],
    [/available credits/gi, 'সারাংশ'],
    [/total batches/gi, 'মোট ব্যাচ'],
    [/total students/gi, 'মোট শিক্ষার্থী'],
    [/attendance today/gi, 'আজকের উপস্থিতি'],
    [/payment failed/gi, 'সম্পূর্ণ হয়নি'],
    [/verification failed/gi, 'যাচাইকরণে সমস্যা'],
    [/registered/gi, 'নিবন্ধিত'],
    [/existing/gi, 'বিদ্যমান'],
    [/custom amount/gi, 'কাস্টম পরিমাণ'],
    [/order summary/gi, 'সারাংশ'],
    [/refresh/gi, 'রিফ্রেশ'],
    [/network/gi, 'নেটওয়ার্ক'],
    [/internet/gi, 'ইন্টারনেট'],
    [/online/gi, 'অনলাইনে'],
    [/offline/gi, 'অফলাইনে'],
    [/settings/gi, 'সেটিংস'],
    [/profile/gi, 'প্রোফাইল'],
    [/wallet/gi, 'অ্যাকাউন্ট'],
    [/credits/gi, 'পরিমাণ'],
    [/credit/gi, 'পরিমাণ'],
    [/transactions/gi, 'কার্যকলাপ'],
    [/transaction/gi, 'কার্যকলাপ'],
    [/login/gi, 'লগইন'],
    [/logout/gi, 'লগআউট'],
    [/support/gi, 'সাপোর্ট'],
    [/admin/gi, 'অ্যাডমিন'],
    [/summary/gi, 'সারাংশ'],
    [/option/gi, 'অপশন'],
    [/batches/gi, 'ব্যাচসমূহ'],
    [/batch/gi, 'ব্যাচ'],
    [/students/gi, 'শিক্ষার্থীরা'],
    [/student/gi, 'শিক্ষার্থী'],
    [/schedules/gi, 'সময়সূচি'],
    [/schedule/gi, 'সময়সূচি'],
    [/sessions/gi, 'সেশনসমূহ'],
    [/session/gi, 'সেশন'],
    [/service/gi, 'সার্ভিস'],
    [/data/gi, 'ডেটা'],
    [/app/gi, 'অ্যাপ'],
    [/flow/gi, 'ফ্লো'],
  ],
  ta: [
    [/terms\s*&\s*conditions/gi, 'விதிமுறைகள் மற்றும் நிபந்தனைகள்'],
    [/privacy policy/gi, 'தனியுரிமைக் கொள்கை'],
    [/institute profile/gi, 'நிறுவன சுயவிவரம்'],
    [/institute details/gi, 'நிறுவன விவரங்கள்'],
    [/institute setup/gi, 'நிறுவன அமைப்பு'],
    [/institute/gi, 'நிறுவனம்'],
    [/dashboard/gi, 'டாஷ்போர்டு'],
    [/home screen/gi, 'முகப்பு திரை'],
    [/quick links/gi, 'விரைவு இணைப்புகள்'],
    [/new batch/gi, 'புதிய பேட்ச்'],
    [/add batch/gi, 'பேட்ச் சேர்க்கவும்'],
    [/batch schedules screen/gi, 'பேட்ச் அட்டவணை திரை'],
    [/batch menu/gi, 'பேட்ச் மெனு'],
    [/all students/gi, 'அனைத்து மாணவர்கள்'],
    [/view students/gi, 'மாணவர்களை காண்க'],
    [/add new student/gi, 'புதிய மாணவரை சேர்க்கவும்'],
    [/add student/gi, 'மாணவரை சேர்க்கவும்'],
    [/mark attendance/gi, 'வருகையை பதிவு செய்யவும்'],
    [/today'?s sessions/gi, 'இன்றைய அமர்வுகள்'],
    [/transaction history/gi, 'செயல்பாட்டு வரலாறு'],
    [/transactions screen/gi, 'செயல்பாட்டுத் திரை'],
    [/wallet\s*&\s*credits/gi, 'கணக்கு மற்றும் சுருக்கம்'],
    [/mobile number/gi, 'மொபைல் எண்'],
    [/country code/gi, 'நாட்டு குறியீடு'],
    [/profile photo/gi, 'சுயவிவர படம்'],
    [/quick contact/gi, 'விரைவு தொடர்பு'],
    [/resend timer/gi, 'மீண்டும் அனுப்பு நேரம்'],
    [/resend otp/gi, 'ஓடிபியை மீண்டும் அனுப்பவும்'],
    [/change/gi, 'மாற்றவும்'],
    [/continue/gi, 'தொடரவும்'],
    [/linked/gi, 'இணைக்கப்பட்ட'],
    [/stat cards/gi, 'புள்ளிவிவர அட்டைகள்'],
    [/card/gi, 'அட்டை'],
    [/view all/gi, 'அனைத்தையும் காண்க'],
    [/calendar/gi, 'காலண்டர்'],
    [/search box/gi, 'தேடல் பெட்டி'],
    [/clear/gi, 'அழிக்கவும்'],
    [/subject/gi, 'பாடம்'],
    [/guardian name/gi, 'பாதுகாவலரின் பெயர்'],
    [/gender/gi, 'பாலினம்'],
    [/type/gi, 'வகை'],
    [/time/gi, 'நேரம்'],
    [/future/gi, 'வரவிருக்கும்'],
    [/records/gi, 'பதிவுகள்'],
    [/class entries/gi, 'வகுப்பு பதிவுகள்'],
    [/class slot/gi, 'வகுப்பு இடைவெளி'],
    [/date range/gi, 'தேதி வரம்பு'],
    [/date/gi, 'தேதி'],
    [/confirmation/gi, 'உறுதிப்படுத்தல்'],
    [/current flow/gi, 'தற்போதைய நடைமுறை'],
    [/submit(?:ted|ting|sion)?/gi, 'சமர்ப்பி'],
    [/save(?:d)?/gi, 'சேமி'],
    [/editable fields/gi, 'திருத்தக்கூடிய புலங்கள்'],
    [/image area/gi, 'பட பகுதி'],
    [/tap/gi, 'தட்டவும்'],
    [/gallery/gi, 'காட்சியகம்'],
    [/organization/gi, 'நிறுவனம்'],
    [/branding assets/gi, 'பிராண்டிங் வளங்கள்'],
    [/sign out/gi, 'வெளியேறவும்'],
    [/secure servers/gi, 'பாதுகாப்பான சர்வர்கள்'],
    [/cached data/gi, 'கேச் செய்யப்பட்ட தரவு'],
    [/available credits/gi, 'சுருக்கம்'],
    [/total batches/gi, 'மொத்த பேட்ச்கள்'],
    [/total students/gi, 'மொத்த மாணவர்கள்'],
    [/attendance today/gi, 'இன்றைய வருகை'],
    [/payment failed/gi, 'முடிக்க முடியவில்லை'],
    [/verification failed/gi, 'சரிபார்ப்பில் சிக்கல்'],
    [/registered/gi, 'பதிவு செய்யப்பட்ட'],
    [/existing/gi, 'ஏற்கனவே உள்ள'],
    [/custom amount/gi, 'தனிப்பயன் தொகை'],
    [/order summary/gi, 'சுருக்கம்'],
    [/refresh/gi, 'ரீஃப்ரெஷ்'],
    [/network/gi, 'நெட்வொர்க்'],
    [/internet/gi, 'இணையம்'],
    [/online/gi, 'ஆன்லைனில்'],
    [/offline/gi, 'ஆஃப்லைனில்'],
    [/settings/gi, 'அமைப்புகள்'],
    [/profile/gi, 'சுயவிவரம்'],
    [/wallet/gi, 'கணக்கு'],
    [/credits/gi, 'அளவு'],
    [/credit/gi, 'அளவு'],
    [/transactions/gi, 'செயல்பாடு'],
    [/transaction/gi, 'செயல்பாடு'],
    [/login/gi, 'லாகின்'],
    [/logout/gi, 'வெளியேறு'],
    [/support/gi, 'ஆதரவு'],
    [/admin/gi, 'அட்மின்'],
    [/summary/gi, 'சுருக்கம்'],
    [/option/gi, 'விருப்பம்'],
    [/batches/gi, 'பேட்ச்கள்'],
    [/batch/gi, 'பேட்ச்'],
    [/students/gi, 'மாணவர்கள்'],
    [/student/gi, 'மாணவர்'],
    [/schedules/gi, 'அட்டவணைகள்'],
    [/schedule/gi, 'அட்டவணை'],
    [/sessions/gi, 'அமர்வுகள்'],
    [/session/gi, 'அமர்வு'],
    [/service/gi, 'சேவை'],
    [/data/gi, 'தரவு'],
    [/app/gi, 'ஆப்'],
    [/flow/gi, 'ஓட்டம்'],
  ],
};

const normalizeHelpFaqText = (
  language: AppLanguage,
  text: string
): string => {
  if (language === 'en') {
    return text;
  }

  return HELP_TERM_REPLACEMENTS[language].reduce(
    (result, [pattern, replacement]) => result.replace(pattern, replacement),
    text
  );
};

export const getLocalizedHelpFaqs = (
  language: AppLanguage
): LocalizedFaqItem[] => {
  const items = HELP_FAQS[language] || HELP_FAQS.en;

  if (language === 'en') {
    return items;
  }

  return items.map((item) => ({
    ...item,
    category: normalizeHelpFaqText(language, item.category),
    question: normalizeHelpFaqText(language, item.question),
    answer: normalizeHelpFaqText(language, item.answer),
  }));
};

export const HELP_FAQS: Record<AppLanguage, LocalizedFaqItem[]> = {
  en: [
    { id: 101, category: 'Getting Started', question: 'How do I get started in the app after login?', answer: 'After login, complete your Institute Profile if prompted. Then create your first batch, add students to that batch, and start marking attendance. Schedules and sessions are helpful later if you want a timetable-based flow.' },
    { id: 102, category: 'Getting Started', question: 'What should I do after institute setup?', answer: 'After saving institute details, create a batch first. Then open Batches, select the batch, add students inside it, and use Mark Attendance directly. Create schedules only when you want classes to appear automatically as sessions.' },
    { id: 103, category: 'Getting Started', question: 'How do I create my first batch and add students?', answer: 'From Dashboard, tap New Batch or open Batches and tap Add Batch. Save the batch, then open it again and use the batch menu to add or view students.' },
    { id: 104, category: 'Getting Started', question: 'How do I mark attendance for the first time?', answer: 'Once students are added to a batch, open Mark Attendance, choose the batch if needed, and submit attendance. If you already use schedules, you can also mark attendance through sessions.' },
    { id: 105, category: 'Getting Started', question: 'Do I need to create a schedule before marking attendance?', answer: 'No. You can create a batch, add students, and mark attendance directly. Schedules are optional and useful only if you want session-wise planned classes.' },
    { id: 1, category: 'Login', question: 'What mobile number should I use to login?', answer: 'Use the 10-digit Indian mobile number registered with your institute. Enter it without country code. You will receive an OTP on this number to sign in.' },
    { id: 2, category: 'Login', question: 'I did not receive the OTP. What should I do?', answer: 'Wait for the resend timer to finish and tap Resend OTP. Check that your number is correct and your network is available. If it still fails, use Change to enter another number or contact securestepsai@gmail.com.' },
    { id: 3, category: 'Login', question: 'Do I need to accept Terms and Privacy before login?', answer: 'Yes. On first launch, you must review and accept the Terms & Conditions and Privacy Policy before continuing to login.' },
    { id: 4, category: 'Account', question: 'How do I reset my password?', answer: 'EduForest uses OTP-based login, so there is no password reset flow. If you cannot access your account, verify the registered mobile number or contact your institute admin or support.' },
    { id: 5, category: 'Account', question: 'Why do I see "Let\'s configure your Institute first"?', answer: 'This means your account is not linked to an institute yet. Tap Continue, fill Institute Profile details, and save to unlock the full app.' },
    { id: 6, category: 'Dashboard', question: 'What do the stat cards on the home screen mean?', answer: 'They summarize your institute data, such as total batches, total students, and attendance marked today. Tapping a card opens the related section.' },
    { id: 7, category: 'Dashboard', question: 'What are "Today\'s Sessions" and how do I use them?', answer: 'These are sessions scheduled for the selected day. You can open a session to mark attendance directly. Use View All to open the complete sessions calendar.' },
    { id: 8, category: 'Batches', question: 'How do I create a new batch?', answer: 'Open Dashboard or Batches and tap Add Batch. Enter a batch name and subject, then save. The batch will appear in your list.' },
    { id: 9, category: 'Batches', question: 'How do I search for a batch?', answer: 'Use the search box on the Batches screen and type a batch name or subject. Clear the search to show all batches again.' },
    { id: 10, category: 'Batches', question: 'What can I do from the batch menu?', answer: 'You can view students, edit the batch, mark attendance, and open schedules for that batch.' },
    { id: 11, category: 'Batches', question: 'I see "No batches found". What should I do?', answer: 'Either no batches exist yet or your search returned no match. Create a new batch or clear the search.' },
    { id: 12, category: 'Students', question: 'How do I add students to a batch?', answer: 'Open the batch, go to View Students, and tap Add Student. You can attach existing students or create new ones and enroll them into the batch.' },
    { id: 13, category: 'Students', question: 'What is the difference between "Add Student" and "Add New Student"?', answer: 'Add Student is batch-focused and can enroll existing or new students into a selected batch. Add New Student creates new students and lets you assign them to one or more batches.' },
    { id: 14, category: 'Students', question: 'What details are required when adding a student?', answer: 'Student name, guardian name, guardian mobile number, and gender are required. In some flows, you can also choose batches.' },
    { id: 15, category: 'Students', question: 'How do I edit or remove a student from a batch?', answer: 'Open the student from a students list. Use edit options to update details, or remove the student from a batch where supported.' },
    { id: 16, category: 'Students', question: 'Where can I see all students across all batches?', answer: 'Open All Students from Dashboard or related navigation. There you can search, view, and manage all students.' },
    { id: 17, category: 'Schedules', question: 'How do I create a schedule for a batch?', answer: 'Open the batch schedules screen, tap Add Schedule, choose schedule type and time, then save. Sessions are generated from schedules.' },
    { id: 18, category: 'Schedules', question: 'What happens if I delete a schedule?', answer: 'Deleting a schedule removes its future sessions. Past records are not removed.' },
    { id: 19, category: 'Schedules', question: 'Why do I see "No schedules found"?', answer: 'No schedules have been added for that batch yet. Add a schedule to start generating sessions.' },
    { id: 20, category: 'Sessions', question: 'What are batch sessions?', answer: 'Sessions are class entries generated from schedules. You can open them and mark attendance for a specific class slot.' },
    { id: 21, category: 'Sessions', question: 'Why does it say "No sessions scheduled for this date"?', answer: 'There may be no schedule matching that date, or the selected date is outside the schedule range. Update or add schedules to generate sessions.' },
    { id: 22, category: 'Sessions', question: 'Can I delete a session?', answer: 'Yes, if the app allows deletion for that session. You will be asked to confirm before it is removed.' },
    { id: 23, category: 'Attendance', question: 'How do I mark attendance?', answer: 'Open Mark Attendance from Home, Quick Links, a batch, or a session. Choose the batch if needed, select statuses for students, and submit while online.' },
    { id: 24, category: 'Attendance', question: 'Can I edit attendance after marking it?', answer: 'No. Once submitted, attendance is treated as final in the current flow. Check carefully before submitting.' },
    { id: 25, category: 'Attendance', question: 'It says "You are offline". Why can\'t I submit?', answer: 'Attendance submission requires internet because records are stored on the server. Reconnect and submit again.' },
    { id: 26, category: 'Attendance', question: 'What do Present, Absent, Leave and Late mean?', answer: 'These are the available attendance states for each student. Choose one status per student for the current session.' },
    { id: 27, category: 'Activity', question: 'Where can I see attendance and class records?', answer: 'Use the dashboard, batch, attendance, and session screens to view the latest saved records for your institute.' },
    { id: 28, category: 'Activity', question: 'How do I confirm that a change was saved?', answer: 'Open the related batch, attendance, or session screen and refresh to verify the latest records.' },
    { id: 29, category: 'Support', question: 'I am seeing an unexpected verification issue. What should I do?', answer: 'Try again after checking your network. If the issue continues, contact support with relevant screenshots and details.' },
    { id: 30, category: 'Support', question: 'A feature is not opening properly. What should I do?', answer: 'Use a recent app build and stable internet connection. If the issue persists, contact support for help.' },
    { id: 31, category: 'Records', question: 'Where can I view recent activity?', answer: 'Recent activity is available in attendance, batch, and session screens depending on the operation performed.' },
    { id: 32, category: 'Records', question: 'Why is my latest update not visible?', answer: 'Refresh the screen or reopen the module. Some updates may take a short time to appear after sync.' },
    { id: 33, category: 'Profile', question: 'How do I update my name, email or mobile?', answer: 'Open Settings and go to Profile. Update editable fields and save. For login mobile number issues, contact support or your admin.' },
    { id: 34, category: 'Profile', question: 'How do I change my profile photo?', answer: 'Tap the profile image area in Profile and choose a photo from your device gallery.' },
    { id: 35, category: 'Profile', question: 'What is Institute Profile and when do I use it?', answer: 'Institute Profile stores your organization details such as name, address, email, mobile, website, and branding assets.' },
    { id: 36, category: 'Settings', question: 'Where do I find Privacy Policy and Terms?', answer: 'Open Settings and use the Privacy & Security or Terms & Conditions options.' },
    { id: 37, category: 'Settings', question: 'How do I logout?', answer: 'Open Settings, scroll down, and tap Logout to sign out of your account.' },
    { id: 38, category: 'Data & Backup', question: 'Is my data backed up?', answer: 'Yes. Core institute data is stored on secure servers and backed up according to the service setup.' },
    { id: 39, category: 'Errors', question: 'I see "You are currently offline". What should I do?', answer: 'Check Wi-Fi or mobile data and try again. Some screens may show cached data, but new submissions require connection.' },
    { id: 40, category: 'Errors', question: 'I see "Server is currently unavailable". What does it mean?', answer: 'The service is temporarily unreachable. Wait a bit and try again. If it continues, contact support.' },
  ],
  hi: [
    { id: 101, category: 'शुरुआत', question: 'लॉगिन के बाद ऐप में शुरुआत कैसे करूं?', answer: 'लॉगिन के बाद यदि कहा जाए तो पहले Institute Profile पूरा करें। फिर पहला बैच बनाएं, उसमें छात्र जोड़ें और उपस्थिति दर्ज करना शुरू करें। टाइमटेबल जैसा flow चाहिए तो बाद में schedules और sessions का उपयोग करें।' },
    { id: 102, category: 'शुरुआत', question: 'Institute setup के बाद क्या करना चाहिए?', answer: 'Institute details save होने के बाद पहले एक batch बनाइए। फिर Batches खोलकर batch चुनिए, उसमें students जोड़िए और सीधे Mark Attendance इस्तेमाल कीजिए। Schedules तब बनाइए जब classes अपने आप sessions के रूप में दिखानी हों।' },
    { id: 103, category: 'शुरुआत', question: 'पहला batch और students कैसे जोड़ूं?', answer: 'Dashboard से New Batch दबाइए या Batches खोलकर Add Batch दबाइए। Batch save करने के बाद उसे फिर खोलिए और batch menu से students add या view कीजिए।' },
    { id: 104, category: 'शुरुआत', question: 'पहली बार attendance कैसे mark करूं?', answer: 'जब batch में students जुड़ जाएं, तब Mark Attendance खोलिए, जरूरत हो तो batch चुनिए और attendance submit कर दीजिए। अगर schedules उपयोग कर रहे हैं तो sessions से भी attendance mark कर सकते हैं।' },
    { id: 105, category: 'शुरुआत', question: 'क्या attendance mark करने से पहले schedule बनाना जरूरी है?', answer: 'नहीं। Batch बनाकर, students जोड़कर आप सीधे attendance mark कर सकते हैं। Schedule केवल session-wise planned classes के लिए जरूरी है।' },
    { id: 1, category: 'लॉगिन', question: 'लॉगिन के लिए कौन सा mobile number उपयोग करूं?', answer: 'अपने institute में registered 10-अंकों वाला Indian mobile number उपयोग करें। Country code के बिना दर्ज करें। इसी नंबर पर OTP आएगा।' },
    { id: 2, category: 'लॉगिन', question: 'OTP नहीं मिला। क्या करूं?', answer: 'Resend timer खत्म होने दें और फिर Resend OTP दबाएं। नंबर और network जांचें। फिर भी समस्या हो तो Change से दूसरा नंबर डालें या support से संपर्क करें।' },
    { id: 3, category: 'लॉगिन', question: 'लॉगिन से पहले Terms और Privacy accept करना जरूरी है?', answer: 'हाँ। पहली बार ऐप खोलने पर आपको Terms & Conditions और Privacy Policy स्वीकार करनी होती है।' },
    { id: 4, category: 'अकाउंट', question: 'पासवर्ड कैसे reset करूं?', answer: 'EduForest OTP-based login उपयोग करता है, इसलिए password reset flow नहीं है। Registered mobile number verify करें या support/contact admin करें।' },
    { id: 5, category: 'अकाउंट', question: '"Let\'s configure your Institute first" क्यों दिखता है?', answer: 'इसका मतलब आपका account अभी institute से linked नहीं है। Continue दबाकर Institute Profile भरें और save करें।' },
    { id: 6, category: 'डैशबोर्ड', question: 'Home screen के stat cards क्या दिखाते हैं?', answer: 'ये total batches, total students और आज की marked attendance जैसी summary दिखाते हैं। Card दबाने पर संबंधित section खुलता है।' },
    { id: 7, category: 'डैशबोर्ड', question: 'Today\'s Sessions क्या हैं और इन्हें कैसे उपयोग करें?', answer: 'ये चुनी हुई तारीख के sessions हैं। किसी session को खोलकर आप सीधे attendance mark कर सकते हैं। View All से पूरा sessions calendar खुलता है।' },
    { id: 8, category: 'बैच', question: 'नया batch कैसे बनाऊं?', answer: 'Dashboard या Batches से Add Batch खोलें, batch name और subject भरें, फिर save करें।' },
    { id: 9, category: 'बैच', question: 'Batch कैसे search करूं?', answer: 'Batches screen पर search box में batch name या subject लिखें। Search clear करने पर सब batches फिर दिखेंगे।' },
    { id: 10, category: 'बैच', question: 'Batch menu से क्या कर सकता हूं?', answer: 'आप students देख सकते हैं, batch edit कर सकते हैं, attendance mark कर सकते हैं और schedules खोल सकते हैं।' },
    { id: 11, category: 'बैच', question: '"No batches found" दिख रहा है। क्या करूं?', answer: 'या तो batch अभी बना नहीं है, या search match नहीं हुआ। नया batch बनाइए या search clear कीजिए।' },
    { id: 12, category: 'छात्र', question: 'Batch में students कैसे जोड़ूं?', answer: 'Batch खोलें, View Students जाएं और Add Student दबाएं। Existing student enroll कर सकते हैं या नया student बना सकते हैं।' },
    { id: 13, category: 'छात्र', question: '"Add Student" और "Add New Student" में क्या फर्क है?', answer: 'Add Student किसी selected batch में student enroll करने के लिए है। Add New Student नए students बनाता है और उन्हें एक या अधिक batches में assign करने देता है।' },
    { id: 14, category: 'छात्र', question: 'Student जोड़ते समय कौन सी जानकारी जरूरी है?', answer: 'Student name, guardian name, guardian mobile number और gender जरूरी हैं। कुछ flows में batch selection भी होता है।' },
    { id: 15, category: 'छात्र', question: 'Student को edit या batch से remove कैसे करूं?', answer: 'Student list से student खोलें। Edit से details बदलें, और जहां supported हो वहां batch से remove करें।' },
    { id: 16, category: 'छात्र', question: 'सभी batches के students कहाँ देखूं?', answer: 'Dashboard या related navigation से All Students खोलें। वहाँ search, view और manage कर सकते हैं।' },
    { id: 17, category: 'शेड्यूल', question: 'Batch के लिए schedule कैसे बनाऊं?', answer: 'Batch schedules screen खोलें, Add Schedule दबाएं, type और time चुनें, फिर save करें। Sessions schedule से बनते हैं।' },
    { id: 18, category: 'शेड्यूल', question: 'Schedule delete करने पर क्या होगा?', answer: 'Schedule delete करने पर उसके future sessions हट जाते हैं। पुराने records नहीं हटते।' },
    { id: 19, category: 'शेड्यूल', question: '"No schedules found" क्यों दिखता है?', answer: 'इस batch के लिए अभी कोई schedule नहीं जोड़ा गया है। Schedule जोड़ने पर sessions बनेंगे।' },
    { id: 20, category: 'सेशंस', question: 'Batch sessions क्या होते हैं?', answer: 'ये schedules से बने class entries हैं। इन्हें खोलकर specific class slot की attendance mark कर सकते हैं।' },
    { id: 21, category: 'सेशंस', question: '"No sessions scheduled for this date" क्यों दिखता है?', answer: 'उस तारीख के लिए schedule match नहीं कर रहा या date schedule range से बाहर है। Schedule update या add करें।' },
    { id: 22, category: 'सेशंस', question: 'क्या session delete कर सकता हूं?', answer: 'हाँ, जहां app अनुमति दे। Delete से पहले confirmation आता है।' },
    { id: 23, category: 'उपस्थिति', question: 'Attendance कैसे mark करूं?', answer: 'Home, Quick Links, batch या session से Mark Attendance खोलें। जरूरत हो तो batch चुनें, students की status set करें और online submit करें।' },
    { id: 24, category: 'उपस्थिति', question: 'Attendance mark होने के बाद edit कर सकता हूं?', answer: 'नहीं। Submit होने के बाद current flow में attendance final मानी जाती है। Submit से पहले जांच लें।' },
    { id: 25, category: 'उपस्थिति', question: '"You are offline" क्यों दिखता है? Submit क्यों नहीं हो रहा?', answer: 'Attendance server पर save होती है, इसलिए submit करने के लिए internet जरूरी है। Connection आने पर फिर submit करें।' },
     { id: 26, category: 'उपस्थिति', question: 'उपस्थित, अनुपस्थित, अवकाश और देरी से का क्या मतलब है?', answer: 'ये प्रत्येक छात्र के लिए उपलब्ध उपस्थिति स्थितियां हैं। वर्तमान सत्र के लिए हर छात्र के सामने इनमें से एक स्थिति चुनें।' },
    { id: 27, category: 'गतिविधि', question: 'उपस्थिति और कक्षा रिकॉर्ड कहाँ देखूं?', answer: 'डैशबोर्ड, बैच, उपस्थिति और सेशन स्क्रीन से अपने संस्थान के नवीनतम सहेजे गए रिकॉर्ड देखें।' },
    { id: 28, category: 'गतिविधि', question: 'बदलाव सहेजा गया है या नहीं, कैसे जांचूं?', answer: 'संबंधित बैच, उपस्थिति या सेशन स्क्रीन खोलकर रिफ्रेश करें और नवीनतम रिकॉर्ड देखें।' },
    { id: 29, category: 'सपोर्ट', question: 'वेरिफिकेशन में समस्या आ रही है। क्या करूं?', answer: 'नेटवर्क जांचकर दोबारा प्रयास करें। समस्या जारी रहे तो स्क्रीनशॉट और विवरण के साथ सपोर्ट से संपर्क करें।' },
    { id: 30, category: 'सपोर्ट', question: 'कोई फीचर ठीक से नहीं खुल रहा। क्या करूं?', answer: 'ऐप का नया बिल्ड और स्थिर इंटरनेट उपयोग करें। फिर भी समस्या रहे तो सपोर्ट से सहायता लें।' },
    { id: 31, category: 'रिकॉर्ड', question: 'हाल की गतिविधि कहाँ दिखती है?', answer: 'हाल की गतिविधि उपस्थिति, बैच और सेशन स्क्रीन में संबंधित क्रिया के अनुसार दिखती है।' },
    { id: 32, category: 'रिकॉर्ड', question: 'मेरा नवीनतम अपडेट क्यों नहीं दिख रहा?', answer: 'स्क्रीन रिफ्रेश करें या मॉड्यूल दोबारा खोलें। सिंक के बाद अपडेट दिखने में थोड़ा समय लग सकता है।' },
    { id: 33, category: 'प्रोफाइल', question: 'अपना नाम, email या mobile कैसे update करूं?', answer: 'Settings में Profile खोलें, editable fields बदलें और save करें। Login mobile number की समस्या हो तो admin या support से संपर्क करें।' },
    { id: 34, category: 'प्रोफाइल', question: 'Profile photo कैसे बदलूं?', answer: 'Profile में image area पर tap करें और gallery से photo चुनें।' },
    { id: 35, category: 'प्रोफाइल', question: 'Institute Profile क्या है और कब उपयोग होता है?', answer: 'Institute Profile में organization का name, address, email, mobile, website और branding assets रखे जाते हैं।' },
    { id: 36, category: 'सेटिंग्स', question: 'Privacy Policy और Terms कहाँ मिलेंगे?', answer: 'Settings खोलें और Privacy & Security या Terms & Conditions option उपयोग करें।' },
    { id: 37, category: 'सेटिंग्स', question: 'Logout कैसे करूं?', answer: 'Settings में नीचे जाएं और Logout दबाकर account से sign out करें।' },
    { id: 38, category: 'डेटा और बैकअप', question: 'क्या मेरा data backed up है?', answer: 'हाँ। मुख्य institute data secure servers पर store और backed up होता है।' },
    { id: 39, category: 'त्रुटियाँ', question: '"You are currently offline" दिख रहा है। क्या करूं?', answer: 'Wi-Fi या mobile data जांचें और फिर कोशिश करें। कुछ screens cached data दिखा सकती हैं, पर नई submission के लिए connection जरूरी है।' },
    { id: 40, category: 'त्रुटियाँ', question: '"Server is currently unavailable" का क्या मतलब है?', answer: 'Service अस्थायी रूप से उपलब्ध नहीं है। थोड़ी देर बाद फिर कोशिश करें। समस्या बनी रहे तो support से संपर्क करें।' },
  ],
  bn: [
    { id: 101, category: 'শুরু', question: 'লগইনের পরে অ্যাপে কীভাবে শুরু করব?', answer: 'লগইনের পরে প্রয়োজন হলে আগে Institute Profile সম্পূর্ণ করুন। তারপর প্রথম ব্যাচ তৈরি করুন, তাতে শিক্ষার্থী যোগ করুন, এবং উপস্থিতি নেওয়া শুরু করুন। টাইমটেবিলভিত্তিক flow চাইলে পরে schedules ও sessions ব্যবহার করুন।' },
    { id: 102, category: 'শুরু', question: 'Institute setup-এর পরে কী করা উচিত?', answer: 'Institute details save হওয়ার পরে আগে একটি batch তৈরি করুন। তারপর Batches খুলে batch নির্বাচন করুন, শিক্ষার্থী যোগ করুন, এবং সরাসরি Mark Attendance ব্যবহার করুন। Session auto-create চাইলে schedules যোগ করুন।' },
    { id: 103, category: 'শুরু', question: 'প্রথম batch এবং শিক্ষার্থী কীভাবে তৈরি করব?', answer: 'Dashboard থেকে New Batch চাপুন বা Batches খুলে Add Batch চাপুন। Batch save করার পরে সেটি খুলে batch menu থেকে students add বা view করুন।' },
    { id: 104, category: 'শুরু', question: 'প্রথমবার attendance কীভাবে নেব?', answer: 'Batch-এ শিক্ষার্থী যুক্ত হলে Mark Attendance খুলুন, প্রয়োজনে batch বেছে নিন, তারপর attendance submit করুন। Schedules ব্যবহার করলে sessions থেকেও নিতে পারবেন।' },
    { id: 105, category: 'শুরু', question: 'Attendance নেওয়ার আগে schedule করা কি জরুরি?', answer: 'না। Batch তৈরি করে শিক্ষার্থী যোগ করেই attendance নেওয়া যায়। Schedule শুধু planned session flow-এর জন্য দরকার।' },
    { id: 1, category: 'লগইন', question: 'লগইনের জন্য কোন mobile number ব্যবহার করব?', answer: 'Institute-এ নিবন্ধিত 10-digit Indian mobile number ব্যবহার করুন। Country code ছাড়া লিখুন। এই নম্বরে OTP আসবে।' },
    { id: 2, category: 'লগইন', question: 'OTP পাইনি। কী করব?', answer: 'Resend timer শেষ হওয়া পর্যন্ত অপেক্ষা করুন, তারপর Resend OTP চাপুন। Number ও network ঠিক আছে কি না দেখুন। সমস্যা থাকলে Change ব্যবহার করুন বা support-এ যোগাযোগ করুন।' },
    { id: 3, category: 'লগইন', question: 'লগইনের আগে Terms ও Privacy accept করা কি দরকার?', answer: 'হ্যাঁ। প্রথমবার অ্যাপ খোলার সময় Terms & Conditions এবং Privacy Policy গ্রহণ করতে হবে।' },
    { id: 4, category: 'অ্যাকাউন্ট', question: 'Password কীভাবে reset করব?', answer: 'EduForest OTP-based login ব্যবহার করে, তাই আলাদা password reset flow নেই। Registered mobile number যাচাই করুন বা support/admin-এর সাথে যোগাযোগ করুন।' },
    { id: 5, category: 'অ্যাকাউন্ট', question: '"Let\'s configure your Institute first" কেন দেখায়?', answer: 'এর মানে আপনার account এখনো institute-এর সাথে linked নয়। Continue চাপুন, Institute Profile পূরণ করুন, এবং save করুন।' },
    { id: 6, category: 'ড্যাশবোর্ড', question: 'Home screen-এর stat cards কী বোঝায়?', answer: 'এগুলো total batches, total students এবং আজকের চিহ্নিত উপস্থিতির মতো summary দেখায়। Card চাপলে সংশ্লিষ্ট section খুলবে।' },
    { id: 7, category: 'ড্যাশবোর্ড', question: 'Today\'s Sessions কী এবং কীভাবে ব্যবহার করব?', answer: 'এগুলো নির্দিষ্ট দিনের sessions। একটি session খুলে সরাসরি attendance নিতে পারবেন। View All চাপলে পুরো sessions calendar খুলবে।' },
    { id: 8, category: 'ব্যাচ', question: 'নতুন batch কীভাবে তৈরি করব?', answer: 'Dashboard বা Batches থেকে Add Batch খুলুন, batch name ও subject লিখুন, তারপর save করুন।' },
    { id: 9, category: 'ব্যাচ', question: 'Batch কীভাবে search করব?', answer: 'Batches screen-এর search box-এ batch name বা subject লিখুন। Clear করলে সব batch আবার দেখা যাবে।' },
    { id: 10, category: 'ব্যাচ', question: 'Batch menu থেকে কী কী করা যায়?', answer: 'Students দেখা, batch edit করা, attendance নেওয়া, এবং schedules খোলা যায়।' },
    { id: 11, category: 'ব্যাচ', question: '"No batches found" দেখাচ্ছে। কী করব?', answer: 'হয় batch এখনো নেই, নয়তো search match পায়নি। নতুন batch তৈরি করুন অথবা search clear করুন।' },
    { id: 12, category: 'শিক্ষার্থী', question: 'Batch-এ শিক্ষার্থী কীভাবে যোগ করব?', answer: 'Batch খুলে View Students-এ যান এবং Add Student চাপুন। Existing student enroll করতে পারবেন, অথবা নতুন student তৈরি করতে পারবেন।' },
    { id: 13, category: 'শিক্ষার্থী', question: '"Add Student" আর "Add New Student"-এর পার্থক্য কী?', answer: 'Add Student নির্দিষ্ট batch-এ enroll করার জন্য। Add New Student নতুন শিক্ষার্থী তৈরি করে এবং একাধিক batch-এ assign করতে দেয়।' },
    { id: 14, category: 'শিক্ষার্থী', question: 'Student যোগ করার সময় কী কী তথ্য লাগে?', answer: 'Student name, guardian name, guardian mobile number, এবং gender দরকার। কিছু flow-তে batch selection-ও থাকে।' },
    { id: 15, category: 'শিক্ষার্থী', question: 'Student edit বা batch থেকে remove কীভাবে করব?', answer: 'Students list থেকে student খুলুন। Edit দিয়ে details বদলান, এবং যেখানে support আছে সেখানে batch থেকে remove করুন।' },
    { id: 16, category: 'শিক্ষার্থী', question: 'সব batch-এর সব students কোথায় দেখব?', answer: 'Dashboard বা related navigation থেকে All Students খুলুন। সেখানে search, view এবং manage করা যাবে।' },
    { id: 17, category: 'সময়সূচি', question: 'Batch-এর জন্য schedule কীভাবে বানাব?', answer: 'Batch schedules screen খুলুন, Add Schedule চাপুন, type এবং time বেছে save করুন। Sessions schedule থেকে তৈরি হয়।' },
    { id: 18, category: 'সময়সূচি', question: 'Schedule delete করলে কী হবে?', answer: 'Schedule delete করলে future sessions মুছে যাবে। আগের records থাকবে।' },
    { id: 19, category: 'সময়সূচি', question: '"No schedules found" কেন দেখায়?', answer: 'এই batch-এর জন্য এখনো কোনো schedule যোগ করা হয়নি। Schedule যোগ করলে sessions তৈরি হবে।' },
    { id: 20, category: 'সেশন', question: 'Batch sessions কী?', answer: 'এগুলো schedule থেকে তৈরি class entries। এগুলো খুলে নির্দিষ্ট class slot-এর attendance নেওয়া যায়।' },
    { id: 21, category: 'সেশন', question: '"No sessions scheduled for this date" কেন দেখায়?', answer: 'ওই তারিখে schedule match করছে না, অথবা date schedule range-এর বাইরে। Schedule update বা add করুন।' },
    { id: 22, category: 'সেশন', question: 'Session delete করা যাবে?', answer: 'হ্যাঁ, যেখানে app অনুমতি দেয়। Delete-এর আগে confirmation আসবে।' },
    { id: 23, category: 'উপস্থিতি', question: 'Attendance কীভাবে নেব?', answer: 'Home, Quick Links, batch বা session থেকে Mark Attendance খুলুন। দরকার হলে batch বেছে নিন, শিক্ষার্থীদের status দিন, এবং online submit করুন।' },
    { id: 24, category: 'উপস্থিতি', question: 'Attendance submit করার পরে edit করা যাবে?', answer: 'না। Submit-এর পরে current flow-এ attendance final ধরা হয়। Submit করার আগে ভালোভাবে দেখে নিন।' },
    { id: 25, category: 'উপস্থিতি', question: '"You are offline" কেন দেখাচ্ছে? Submit কেন হচ্ছে না?', answer: 'Attendance server-এ save হয়, তাই submit করতে internet দরকার। Connection এলে আবার submit করুন।' },
     { id: 26, category: 'উপস্থিতি', question: 'উপস্থিত, অনুপস্থিত, ছুটি এবং দেরি মানে কী?', answer: 'এগুলো প্রতিটি শিক্ষার্থীর জন্য উপস্থিতির অবস্থা। বর্তমান সেশনের জন্য প্রতিটি শিক্ষার্থীর পাশে একটি অবস্থা নির্বাচন করুন।' },
    { id: 27, category: 'কার্যকলাপ', question: 'উপস্থিতি ও ক্লাস রেকর্ড কোথায় দেখব?', answer: 'ড্যাশবোর্ড, ব্যাচ, উপস্থিতি ও সেশন স্ক্রিন ব্যবহার করে আপনার প্রতিষ্ঠানের সর্বশেষ সংরক্ষিত রেকর্ড দেখুন।' },
    { id: 28, category: 'কার্যকলাপ', question: 'পরিবর্তন সংরক্ষিত হয়েছে কি না কীভাবে নিশ্চিত হব?', answer: 'সংশ্লিষ্ট ব্যাচ, উপস্থিতি বা সেশন স্ক্রিন খুলে রিফ্রেশ করে সর্বশেষ রেকর্ড দেখুন।' },
    { id: 29, category: 'সাপোর্ট', question: 'যাচাইকরণে সমস্যা হচ্ছে। কী করব?', answer: 'নেটওয়ার্ক পরীক্ষা করে আবার চেষ্টা করুন। সমস্যা থাকলে স্ক্রিনশটসহ সাপোর্টে যোগাযোগ করুন।' },
    { id: 30, category: 'সাপোর্ট', question: 'কোনো ফিচার ঠিকমতো খুলছে না। কী করব?', answer: 'অ্যাপের নতুন বিল্ড ও স্থিতিশীল ইন্টারনেট ব্যবহার করুন। তারপরও সমস্যা থাকলে সাপোর্টে জানান।' },
    { id: 31, category: 'রেকর্ড', question: 'সাম্প্রতিক কার্যক্রম কোথায় দেখা যায়?', answer: 'যে কাজ করা হয়েছে তার ভিত্তিতে উপস্থিতি, ব্যাচ ও সেশন স্ক্রিনে সাম্প্রতিক কার্যক্রম দেখা যায়।' },
    { id: 32, category: 'রেকর্ড', question: 'আমার সর্বশেষ আপডেট কেন দেখা যাচ্ছে না?', answer: 'স্ক্রিন রিফ্রেশ করুন বা মডিউল আবার খুলুন। সিঙ্কের পর আপডেট দেখাতে কিছুটা সময় লাগতে পারে।' },
    { id: 33, category: 'প্রোফাইল', question: 'নাম, email বা mobile কীভাবে update করব?', answer: 'Settings থেকে Profile খুলে editable fields বদলে save করুন। Login mobile number-এর সমস্যায় admin বা support-এর সাথে কথা বলুন।' },
    { id: 34, category: 'প্রোফাইল', question: 'Profile photo কীভাবে বদলাব?', answer: 'Profile-এ image area-তে tap করে gallery থেকে photo বেছে নিন।' },
    { id: 35, category: 'প্রোফাইল', question: 'Institute Profile কী এবং কখন ব্যবহার করব?', answer: 'Institute Profile-এ organization-এর name, address, email, mobile, website ও branding assets থাকে।' },
    { id: 36, category: 'সেটিংস', question: 'Privacy Policy এবং Terms কোথায় পাব?', answer: 'Settings খুলে Privacy & Security অথবা Terms & Conditions option ব্যবহার করুন।' },
    { id: 37, category: 'সেটিংস', question: 'Logout কীভাবে করব?', answer: 'Settings-এ নিচে গিয়ে Logout চাপুন এবং account থেকে sign out করুন।' },
    { id: 38, category: 'ডেটা ও ব্যাকআপ', question: 'আমার data কি backed up হয়?', answer: 'হ্যাঁ। মূল institute data secure servers-এ store হয় এবং backed up থাকে।' },
    { id: 39, category: 'ত্রুটি', question: '"You are currently offline" দেখাচ্ছে। কী করব?', answer: 'Wi-Fi বা mobile data পরীক্ষা করুন এবং আবার চেষ্টা করুন। কিছু screen cached data দেখাতে পারে, কিন্তু নতুন submission-এর জন্য connection দরকার।' },
    { id: 40, category: 'ত্রুটি', question: '"Server is currently unavailable" মানে কী?', answer: 'Service সাময়িকভাবে unavailable। কিছুক্ষণ পরে আবার চেষ্টা করুন। সমস্যা থাকলে support-এ যোগাযোগ করুন।' },
  ],
  ta: [
    { id: 101, category: 'தொடக்கம்', question: 'Login ஆன பிறகு app-ஐ எப்படி தொடங்குவது?', answer: 'தேவைப்பட்டால் முதலில் Institute Profile-ஐ முடிக்கவும். பிறகு முதல் batch-ஐ உருவாக்கி, அதில் மாணவர்களை சேர்த்து, attendance பதிவு செய்ய தொடங்கவும். Timetable flow வேண்டுமெனில் பின்னர் schedules மற்றும் sessions பயன்படுத்தலாம்.' },
    { id: 102, category: 'தொடக்கம்', question: 'Institute setup ஆன பிறகு என்ன செய்ய வேண்டும்?', answer: 'Institute details save ஆன பிறகு முதலில் ஒரு batch உருவாக்குங்கள். பின்னர் Batches-ஐ திறந்து batch-ஐ தேர்வு செய்து, students-ஐ சேர்த்து, Mark Attendance-ஐ பயன்படுத்துங்கள். Classes auto session ஆக வேண்டுமெனில் schedules சேர்க்கவும்.' },
    { id: 103, category: 'தொடக்கம்', question: 'முதல் batch மற்றும் students-ஐ எப்படி சேர்ப்பது?', answer: 'Dashboard-இல் New Batch அழுத்தவும் அல்லது Batches-இல் Add Batch திறக்கவும். Batch save ஆன பின் அதை மீண்டும் திறந்து batch menu மூலம் students-ஐ add அல்லது view செய்யவும்.' },
    { id: 104, category: 'தொடக்கம்', question: 'முதல் முறையாக attendance எப்படி mark செய்வது?', answer: 'Batch-இல் students சேர்ந்த பிறகு Mark Attendance திறந்து, தேவைப்பட்டால் batch தேர்வு செய்து attendance submit செய்யவும். Schedules பயன்படுத்தினால் sessions வழியாகவும் mark செய்யலாம்.' },
    { id: 105, category: 'தொடக்கம்', question: 'Attendance mark செய்வதற்கு முன் schedule அவசியமா?', answer: 'இல்லை. Batch உருவாக்கி students சேர்த்தவுடன் நேரடியாக attendance mark செய்யலாம். Session-wise planned flow வேண்டும் என்றால் மட்டுமே schedule தேவை.' },
    { id: 1, category: 'Login', question: 'Login செய்ய எந்த mobile number பயன்படுத்த வேண்டும்?', answer: 'Institute-இல் பதிவு செய்யப்பட்ட 10 digit Indian mobile number பயன்படுத்தவும். Country code இல்லாமல் உள்ளிடவும். இந்த எண்ணிற்கே OTP வரும்.' },
    { id: 2, category: 'Login', question: 'OTP வரவில்லை. என்ன செய்ய வேண்டும்?', answer: 'Resend timer முடியும் வரை காத்திருந்து Resend OTP அழுத்தவும். Number மற்றும் network சரியா என்று பார்க்கவும். இன்னும் சிக்கல் இருந்தால் Change மூலம் வேறு number கொடுக்கவும் அல்லது support-ஐ தொடர்பு கொள்ளவும்.' },
    { id: 3, category: 'Login', question: 'Login செய்யும் முன் Terms மற்றும் Privacy accept செய்ய வேண்டுமா?', answer: 'ஆம். App-ஐ முதன்முதலில் திறக்கும் போது Terms & Conditions மற்றும் Privacy Policy-ஐ ஏற்க வேண்டும்.' },
    { id: 4, category: 'கணக்கு', question: 'Password-ஐ எப்படி reset செய்வது?', answer: 'EduForest OTP-based login பயன்படுத்துகிறது. தனியான password reset flow இல்லை. Registered mobile number சரியாக உள்ளதா பார்க்கவும் அல்லது support/admin-ஐ அணுகவும்.' },
    { id: 5, category: 'கணக்கு', question: '"Let\'s configure your Institute first" ஏன் வருகிறது?', answer: 'உங்கள் account இன்னும் institute-இன் সাথে link ஆகவில்லை என்பதைக் குறிக்கிறது. Continue அழுத்தி Institute Profile நிரப்பி save செய்யவும்.' },
    { id: 6, category: 'டாஷ்போர்டு', question: 'Home screen stat cards என்ன காட்டும்?', answer: 'இவை total batches, total students மற்றும் இன்று பதிவு செய்யப்பட்ட வருகை போன்ற summary-ஐ காட்டும். Card அழுத்தினால் தொடர்புடைய section திறக்கும்.' },
    { id: 7, category: 'டாஷ்போர்டு', question: 'Today\'s Sessions என்றால் என்ன? அதை எப்படி பயன்படுத்துவது?', answer: 'அந்த நாளுக்கான sessions இவை. ஒரு session-ஐ திறந்து நேரடியாக attendance mark செய்யலாம். View All மூலம் முழு sessions calendar திறக்கும்.' },
    { id: 8, category: 'Batch', question: 'புதிய batch எப்படி உருவாக்குவது?', answer: 'Dashboard அல்லது Batches-இல் Add Batch திறந்து batch name மற்றும் subject கொடுத்து save செய்யவும்.' },
    { id: 9, category: 'Batch', question: 'Batch-ஐ எப்படி search செய்வது?', answer: 'Batches screen-இன் search box-இல் batch name அல்லது subject type செய்யவும். Search clear செய்தால் எல்லா batches மீண்டும் தெரியும்.' },
    { id: 10, category: 'Batch', question: 'Batch menu மூலம் என்ன செய்யலாம்?', answer: 'Students-ஐ பார்க்கலாம், batch edit செய்யலாம், attendance mark செய்யலாம், schedules திறக்கலாம்.' },
    { id: 11, category: 'Batch', question: '"No batches found" என்று வருகிறது. என்ன செய்வது?', answer: 'Batch இன்னும் உருவாக்கப்படவில்லை அல்லது search match இல்லை. புதிய batch உருவாக்குங்கள் அல்லது search clear செய்யுங்கள்.' },
    { id: 12, category: 'மாணவர்கள்', question: 'Batch-க்கு students எப்படி சேர்ப்பது?', answer: 'Batch திறந்து View Students செல்லவும், பிறகு Add Student அழுத்தவும். Existing student-ஐ enroll செய்யலாம் அல்லது புதிய student உருவாக்கலாம்.' },
    { id: 13, category: 'மாணவர்கள்', question: '"Add Student" மற்றும் "Add New Student" வித்தியாசம் என்ன?', answer: 'Add Student என்பது குறிப்பிட்ட batch-க்கு enroll செய்ய பயன்படும். Add New Student புதிய students உருவாக்கி, ஒரே நேரத்தில் பல batches-க்கு assign செய்ய உதவும்.' },
    { id: 14, category: 'மாணவர்கள்', question: 'Student சேர்க்கும்போது எந்த தகவல்கள் தேவை?', answer: 'Student name, guardian name, guardian mobile number, gender அவசியம். சில flows-ல் batch selection-வும் இருக்கும்.' },
    { id: 15, category: 'மாணவர்கள்', question: 'Student-ஐ edit அல்லது batch-இல் இருந்து remove செய்வது எப்படி?', answer: 'Students list-இல் இருந்து student திறக்கவும். Edit மூலம் details update செய்யவும், support உள்ள இடங்களில் batch-இல் இருந்து remove செய்யவும்.' },
    { id: 16, category: 'மாணவர்கள்', question: 'எல்லா batches-இன் students-ஐ எங்கே பார்க்கலாம்?', answer: 'Dashboard அல்லது தொடர்புடைய navigation-இல் All Students திறக்கவும். அங்கே search, view, manage செய்யலாம்.' },
    { id: 17, category: 'அட்டவணை', question: 'Batch-க்கான schedule எப்படி உருவாக்குவது?', answer: 'Batch schedules screen-ஐ திறந்து Add Schedule அழுத்தி type, time தேர்வு செய்து save செய்யவும். Sessions schedule-இலிருந்து உருவாகும்.' },
    { id: 18, category: 'அட்டவணை', question: 'Schedule delete செய்தால் என்ன ஆகும்?', answer: 'Schedule delete செய்தால் future sessions நீக்கப்படும். பழைய records இருக்கும்.' },
    { id: 19, category: 'அட்டவணை', question: '"No schedules found" ஏன் வருகிறது?', answer: 'இந்த batch-க்கு இன்னும் எந்த schedule-மும் சேர்க்கப்படவில்லை. Schedule சேர்த்தால் sessions உருவாகும்.' },
    { id: 20, category: 'Sessions', question: 'Batch sessions என்றால் என்ன?', answer: 'இவை schedule-இலிருந்து உருவான class entries. இவற்றைத் திறந்து குறிப்பிட்ட class slot-இன் attendance mark செய்யலாம்.' },
    { id: 21, category: 'Sessions', question: '"No sessions scheduled for this date" ஏன் வருகிறது?', answer: 'அந்த தேதிக்கு schedule பொருந்தவில்லை அல்லது தேதி schedule range-க்கு வெளியே உள்ளது. Schedule update அல்லது add செய்யவும்.' },
    { id: 22, category: 'Sessions', question: 'Session delete செய்யலாமா?', answer: 'ஆம், app அனுமதித்தால் delete செய்யலாம். Delete செய்வதற்கு முன் confirmation வரும்.' },
    { id: 23, category: 'வருகை', question: 'Attendance எப்படி mark செய்வது?', answer: 'Home, Quick Links, batch அல்லது session-இல் இருந்து Mark Attendance திறக்கவும். தேவைப்பட்டால் batch தேர்வு செய்து, status அமைத்து online submit செய்யவும்.' },
    { id: 24, category: 'வருகை', question: 'Attendance submit செய்த பிறகு edit செய்ய முடியுமா?', answer: 'இல்லை. Submit ஆன பிறகு current flow-இல் attendance final ஆக கருதப்படும். Submit செய்வதற்கு முன் சரிபார்க்கவும்.' },
    { id: 25, category: 'வருகை', question: '"You are offline" என்று ஏன் வருகிறது? Submit ஏன் ஆகவில்லை?', answer: 'Attendance server-இல் save ஆகிறது. Submit செய்ய internet தேவை. Connection வந்த பிறகு மீண்டும் submit செய்யவும்.' },
     { id: 26, category: 'வருகை', question: 'வருகை, வரவில்லை, விடுப்பு, தாமதம் என்றால் என்ன?', answer: 'இவை ஒவ்வொரு மாணவருக்கும் பயன்படுத்தப்படும் வருகை நிலைகள். தற்போதைய அமர்விற்காக ஒவ்வொரு மாணவருக்கும் இதில் ஒரு நிலையைத் தேர்வு செய்யவும்.' },
    { id: 27, category: 'செயல்பாடு', question: 'வருகை மற்றும் வகுப்பு பதிவுகளை எங்கே பார்க்கலாம்?', answer: 'டாஷ்போர்டு, பேட்ச், வருகை மற்றும் அமர்வு திரைகள் மூலம் உங்கள் நிறுவனத்தின் சமீபத்திய சேமிக்கப்பட்ட பதிவுகளைக் காணலாம்.' },
    { id: 28, category: 'செயல்பாடு', question: 'மாற்றம் சேமிக்கப்பட்டதா என்பதை எப்படி உறுதிப்படுத்துவது?', answer: 'தொடர்புடைய பேட்ச், வருகை அல்லது அமர்வு திரையை திறந்து ரீஃப்ரெஷ் செய்து சமீபத்திய பதிவுகளை பார்க்கவும்.' },
    { id: 29, category: 'ஆதரவு', question: 'சரிபார்ப்பில் சிக்கல் வருகிறது. என்ன செய்ய வேண்டும்?', answer: 'நெட்வொர்க்கை சரிபார்த்து மீண்டும் முயற்சிக்கவும். சிக்கல் தொடர்ந்தால் ஸ்கிரீன்ஷாட் மற்றும் விவரங்களுடன் ஆதரவை தொடர்பு கொள்ளவும்.' },
    { id: 30, category: 'ஆதரவு', question: 'ஒரு அம்சம் சரியாக திறக்கவில்லை. என்ன செய்ய வேண்டும்?', answer: 'புதிய app build மற்றும் நிலையான இணைய இணைப்பைப் பயன்படுத்தவும். சிக்கல் நீடித்தால் ஆதரவிடம் உதவி பெறவும்.' },
    { id: 31, category: 'பதிவுகள்', question: 'சமீபத்திய செயல்பாடுகளை எங்கு பார்க்கலாம்?', answer: 'செயல்பாட்டின் தன்மைக்கு ஏற்ப வருகை, பேட்ச் மற்றும் அமர்வு திரைகளில் சமீபத்திய செயல்பாடுகள் காணப்படும்.' },
    { id: 32, category: 'பதிவுகள்', question: 'என் சமீபத்திய புதுப்பிப்பு ஏன் தெரியவில்லை?', answer: 'திரையை ரீஃப்ரெஷ் செய்யவும் அல்லது மாட்யூலை மீண்டும் திறக்கவும். ஒத்திசைவு பிறகு புதுப்பிப்பு தெரிய சிறிது நேரம் ஆகலாம்.' },
    { id: 33, category: 'Profile', question: 'என் பெயர், email அல்லது mobile-ஐ எப்படி update செய்வது?', answer: 'Settings-இல் Profile திறந்து editable fields update செய்து save செய்யவும். Login mobile number பிரச்சினைக்கு admin அல்லது support-ஐ அணுகவும்.' },
    { id: 34, category: 'Profile', question: 'Profile photo எப்படி மாற்றுவது?', answer: 'Profile-இல் image area-ஐ tap செய்து gallery-இலிருந்து photo தேர்வு செய்யவும்.' },
    { id: 35, category: 'Profile', question: 'Institute Profile என்றால் என்ன? எப்போது பயன்படுத்த வேண்டும்?', answer: 'Institute Profile-இல் organization name, address, email, mobile, website, branding assets போன்றவை சேமிக்கப்படும்.' },
    { id: 36, category: 'Settings', question: 'Privacy Policy மற்றும் Terms எங்கே கிடைக்கும்?', answer: 'Settings திறந்து Privacy & Security அல்லது Terms & Conditions option-ஐ பயன்படுத்தவும்.' },
    { id: 37, category: 'Settings', question: 'Logout எப்படி செய்வது?', answer: 'Settings-இல் கீழே சென்று Logout அழுத்தி account-இலிருந்து sign out செய்யவும்.' },
    { id: 38, category: 'Data & Backup', question: 'என் data backed up ஆகிறதா?', answer: 'ஆம். முக்கிய institute data secure servers-இல் சேமிக்கப்பட்டு backed up இருக்கும்.' },
    { id: 39, category: 'பிழைகள்', question: '"You are currently offline" என்று வருகிறது. என்ன செய்வது?', answer: 'Wi-Fi அல்லது mobile data சரிபார்த்து மீண்டும் முயற்சிக்கவும். சில screens cached data காட்டலாம், ஆனால் புதிய submission-க்கு connection தேவை.' },
    { id: 40, category: 'பிழைகள்', question: '"Server is currently unavailable" என்றால் என்ன?', answer: 'Service தற்காலிகமாக கிடைக்கவில்லை. சில நேரம் கழித்து மீண்டும் முயற்சிக்கவும். தொடர்ந்தால் support-ஐ தொடர்பு கொள்ளவும்.' },
  ],
};

/** Parent app (EduForest Parent) help FAQs — not institute / Gentrack flows. */
export const PARENT_HELP_FAQS: Record<AppLanguage, LocalizedFaqItem[]> = {
  en: [
    {
      id: 1,
      category: 'Getting started',
      question: 'What is the EduForest Parent app for?',
      answer:
        'You receive attendance updates when your child’s institute marks attendance using EduForest. Open Home to see a snapshot, Attendance for history, and Alerts for notifications.',
    },
    {
      id: 2,
      category: 'Login',
      question: 'Which mobile number should I use?',
      answer:
        'Use the same 10-digit Indian mobile number your institute registered as the guardian contact for your child. Sign-in uses SMS OTP (Firebase) on this number.',
    },
    {
      id: 3,
      category: 'Login',
      question: 'I did not receive the OTP. What should I do?',
      answer:
        'Wait for the resend timer, then tap Resend OTP. Check the number, signal, and SMS blocking settings. You can tap Change to edit the number. If it still fails, email securestepsai@gmail.com.',
    },
    {
      id: 4,
      category: 'Notifications',
      question: 'Why am I not getting attendance alerts?',
      answer:
        'Allow notifications for EduForest Parent in system settings. The institute must mark attendance and have your correct guardian number on file. Stay online for the best experience.',
    },
    {
      id: 5,
      category: 'Voice',
      question: 'What are voice announcements?',
      answer:
        'When enabled under Profile, the app can speak the attendance message when a push arrives in the foreground. You can turn this off anytime from Profile.',
    },
    {
      id: 6,
      category: 'Attendance',
      question: 'Where can I see past attendance?',
      answer:
        'Open the Attendance tab for history and summaries. Home may show recent highlights depending on your institute’s setup.',
    },
    {
      id: 7,
      category: 'Privacy',
      question: 'Where are the Privacy Policy and Terms?',
      answer:
        'Open Profile, then Privacy policy, Terms & conditions, or Help & support. You can also read the same policies on https://eduforest.co.in.',
    },
    {
      id: 8,
      category: 'Support',
      question: 'Who do I contact for wrong attendance or account issues?',
      answer:
        'Contact your institute first—they manage records. For app or login issues, email securestepsai@gmail.com with your registered mobile number and a short description.',
    },
    {
      id: 9,
      category: 'Notifications & privacy',
      question: 'What data is used for push notifications?',
      answer:
        'Your institute sends attendance updates through EduForest; our servers may store an FCM device token linked to your parent account so alerts can reach your phone. Message content is used to show the alert in the app. See the in-app Privacy Policy for full details.',
    },
    {
      id: 10,
      category: 'Notifications & privacy',
      question: 'Does voice announcement send my voice to the server?',
      answer:
        'No. Voice announcements use your phone’s built-in text-to-speech to read the message locally when the app is active and the feature is on in Profile. It is not a recording sent to EduForest.',
    },
  ],
  hi: [
    {
      id: 1,
      category: 'शुरुआत',
      question: 'EduForest Parent ऐप किस लिए है?',
      answer:
        'जब आपके बच्चे का संस्थान EduForest से उपस्थिति दर्ज करता है तो आपको अपडेट मिलते हैं। सारांश के लिए Home, इतिहास के लिए Attendance, और सूचनाओं के लिए Alerts खोलें।',
    },
    {
      id: 2,
      category: 'लॉगिन',
      question: 'कौन सा मोबाइल नंबर उपयोग करूँ?',
      answer:
        'वही 10 अंकों का भारतीय मोबाइल नंबर उपयोग करें जो संस्थान ने आपके बच्चे के अभिभावक संपर्क के रूप में दर्ज किया है। साइन-इन इसी नंबर पर SMS OTP (Firebase) से होता है।',
    },
    {
      id: 3,
      category: 'लॉगिन',
      question: 'OTP नहीं मिला। क्या करूँ?',
      answer:
        'रीसेंड टाइमर खत्म होने दें, फिर Resend OTP दबाएँ। नंबर, नेटवर्क और SMS ब्लॉक सेटिंग जाँचें। नंबर बदलने के लिए Change दबाएँ। फिर भी असफल हो तो securestepsai@gmail.com पर लिखें।',
    },
    {
      id: 4,
      category: 'सूचनाएँ',
      question: 'उपस्थिति अलर्ट क्यों नहीं मिल रहे?',
      answer:
        'सिस्टम सेटिंग में EduForest Parent के लिए सूचनाएँ अनुमति दें। संस्थान को उपस्थिति दर्ज करनी होगी और फाइल पर सही अभिभावक नंबर होना चाहिए। बेहतर अनुभव के लिए ऑनलाइन रहें।',
    },
    {
      id: 5,
      category: 'आवाज़',
      question: 'आवाज़ घोषणाएँ क्या हैं?',
      answer:
        'प्रोफ़ाइल में चालू करने पर, जब ऐप अग्रभूमि में हो और पुश आए तो ऐप उपस्थिति संदेश बोलकर सुना सकता है। इसे कभी भी प्रोफ़ाइल से बंद कर सकते हैं।',
    },
    {
      id: 6,
      category: 'उपस्थिति',
      question: 'पुरानी उपस्थिति कहाँ देखूँ?',
      answer:
        'इतिहास और सारांश के लिए Attendance टैब खोलें। संस्थान की सेटअप के अनुसार Home पर हाल की हाइलाइट्स दिख सकती हैं।',
    },
    {
      id: 7,
      category: 'गोपनीयता',
      question: 'प्राइवेसी पॉलिसी और नियम कहाँ हैं?',
      answer:
        'प्रोफ़ाइल खोलें, फिर प्राइवेसी पॉलिसी, नियम और शर्तें, या मदद और सपोर्ट। https://eduforest.co.in पर भी पढ़ सकते हैं।',
    },
    {
      id: 8,
      category: 'सपोर्ट',
      question: 'गलत उपस्थिति या खाते की समस्या पर किससे संपर्क करूँ?',
      answer:
        'पहले अपने संस्थान से संपर्क करें—वे रिकॉर्ड प्रबंधित करते हैं। ऐप या लॉगिन के लिए अपना पंजीकृत मोबाइल और संक्षिप्त विवरण के साथ securestepsai@gmail.com पर लिखें।',
    },
    {
      id: 9,
      category: 'सूचनाएँ और गोपनीयता',
      question: 'पुश सूचनाओं के लिए कौन सा डेटा उपयोग होता है?',
      answer:
        'संस्थान EduForest के जरिए उपस्थिति अपडेट भेजता है; अलर्ट आपके फोन तक पहुँचाने के लिए हमारे सर्वर आपके पैरेंट खाते से जुड़ा FCM डिवाइस टोकन संग्रहीत कर सकते हैं। संदेश ऐप में अलर्ट दिखाने के लिए उपयोग होते हैं। पूरी जानकारी इन-ऐप प्राइवेसी पॉलिसी में है।',
    },
    {
      id: 10,
      category: 'सूचनाएँ और गोपनीयता',
      question: 'क्या आवाज़ घोषणा मेरी आवाज़ सर्वर पर भेजती है?',
      answer:
        'नहीं। आवाज़ घोषणाएँ ऐप सक्रिय और प्रोफ़ाइल में सुविधा चालू होने पर आपके फोन के टेक्स्ट-टू-स्पीच से स्थानीय रूप से संदेश पढ़ती हैं। EduForest को रिकॉर्डिंग नहीं भेजी जाती।',
    },
  ],
  bn: [
    {
      id: 1,
      category: 'শুরু',
      question: 'EduForest Parent অ্যাপটি কীসের জন্য?',
      answer:
        'আপনার সন্তানের প্রতিষ্ঠান EduForest দিয়ে উপস্থিতি চিহ্নিত করলে আপনি আপডেট পাবেন। সারসংক্ষেপের জন্য Home, ইতিহাসের জন্য Attendance, এবং বিজ্ঞপ্তির জন্য Alerts খুলুন।',
    },
    {
      id: 2,
      category: 'লগইন',
      question: 'কোন মোবাইল নম্বর ব্যবহার করব?',
      answer:
        'আপনার সন্তানের অভিভাবক যোগাযোগ হিসেবে প্রতিষ্ঠান যে ১০ সংখ্যার ভারতীয় মোবাইল নম্বর নিবন্ধন করেছে সেটিই ব্যবহার করুন। এই নম্বরে SMS OTP (Firebase) দিয়ে সাইন-ইন হয়।',
    },
    {
      id: 3,
      category: 'লগইন',
      question: 'OTP পাইনি। কী করব?',
      answer:
        'রিসেন্ড টাইমার শেষ হওয়ার অপেক্ষা করুন, তারপর Resend OTP চাপুন। নম্বর, নেটওয়ার্ক ও SMS ব্লক সেটিংস দেখুন। নম্বর বদলাতে Change চাপুন। ব্যর্থ হলে securestepsai@gmail.com-এ লিখুন।',
    },
    {
      id: 4,
      category: 'বিজ্ঞপ্তি',
      question: 'উপস্থিতি অ্যালার্ট পাচ্ছি না কেন?',
      answer:
        'সিস্টেম সেটিংসে EduForest Parent-এর জন্য বিজ্ঞপ্তি অনুমতি দিন। প্রতিষ্ঠানকে উপস্থিতি চিহ্নিত করতে হবে এবং ফাইলে সঠিক অভিভাবক নম্বর থাকতে হবে। ভালো অভিজ্ঞতার জন্য অনলাইন থাকুন।',
    },
    {
      id: 5,
      category: 'ভয়েস',
      question: 'ভয়েস ঘোষণা কী?',
      answer:
        'প্রোফাইলে চালু থাকলে, অ্যাগ্রগ্রাউন্ডে পুশ এলে অ্যাপ উপস্থিতি বার্তা জোরে পড়তে পারে। যেকোনো সময় প্রোফাইল থেকে বন্ধ করতে পারবেন।',
    },
    {
      id: 6,
      category: 'উপস্থিতি',
      question: 'আগের উপস্থিতি কোথায় দেখব?',
      answer:
        'ইতিহাস ও সারাংশের জন্য Attendance ট্যাব খুলুন। প্রতিষ্ঠানের সেটআপ অনুযায়ী Home-এ সাম্প্রতিক হাইলাইট দেখা যেতে পারে।',
    },
    {
      id: 7,
      category: 'গোপনীয়তা',
      question: 'প্রাইভেসি পলিসি ও শর্তাবলী কোথায়?',
      answer:
        'প্রোফাইল খুলুন, তারপর প্রাইভেসি পলিসি, শর্তাবলী, বা সহায়তা। https://eduforest.co.in-এও পড়তে পারেন।',
    },
    {
      id: 8,
      category: 'সাপোর্ট',
      question: 'ভুল উপস্থিতি বা অ্যাকাউন্ট সমস্যায় কাকে জানাব?',
      answer:
        'প্রথমে আপনার প্রতিষ্ঠানে যোগাযোগ করুন—তারা রেকর্ড পরিচালনা করে। অ্যাপ বা লগইনের জন্য নিবন্ধিত মোবাইল ও সংক্ষিপ্ত বিবরণ সহ securestepsai@gmail.com-এ লিখুন।',
    },
    {
      id: 9,
      category: 'বিজ্ঞপ্তি ও গোপনীয়তা',
      question: 'পুশ বিজ্ঞপ্তির জন্য কোন ডেটা ব্যবহার হয়?',
      answer:
        'প্রতিষ্ঠান EduForest-এর মাধ্যমে উপস্থিতি আপডেট পাঠায়; আমাদের সার্ভার আপনার প্যারেন্ট অ্যাকাউন্টের সাথে যুক্ত FCM ডিভাইস টোকেন সংরক্ষণ করতে পারে যাতে অ্যালার্ট ফোনে পৌঁছায়। বার্তা অ্যাপে দেখানোর জন্য ব্যবহৃত হয়। পূর্ণ বিবরণ ইন-অ্যাপ প্রাইভেসি পলিসিতে।',
    },
    {
      id: 10,
      category: 'বিজ্ঞপ্তি ও গোপনীয়তা',
      question: 'ভয়েস ঘোষণা কি আমার কণ্ঠ সার্ভারে পাঠায়?',
      answer:
        'না। অ্যাপ সক্রিয় ও প্রোফাইলে বৈশিষ্ট্য চালু থাকলে ভয়েস ঘোষণা ডিভাইসের টেক্সট-টু-স্পিচ দিয়ে স্থানীয়ভাবে বার্তা পড়ে। EduForest-এ রেকর্ডিং পাঠানো হয় না।',
    },
  ],
  ta: [
    {
      id: 1,
      category: 'தொடக்கம்',
      question: 'EduForest Parent செயலி எதற்காக?',
      answer:
        'உங்கள் குழந்தையின் நிறுவனம் EduForest மூலம் வருகையை பதிவு செய்யும்போது புதுப்பிப்புகளைப் பெறுவீர்கள். சுருக்கத்திற்கு Home, வரலாற்றிற்கு Attendance, அறிவிப்புகளுக்கு Alerts திறக்கவும்.',
    },
    {
      id: 2,
      category: 'உள்நுழைவு',
      question: 'எந்த மொபைல் எண்ணைப் பயன்படுத்த வேண்டும்?',
      answer:
        'நிறுவனம் உங்கள் குழந்தைக்கு பாதுகாவலர் தொடர்பாக பதிவு செய்த அதே 10 இலக்க இந்திய மொபைல் எண்ணைப் பயன்படுத்தவும். இந்த எண்ணில் SMS OTP (Firebase) மூலம் உள்நுழைவு.',
    },
    {
      id: 3,
      category: 'உள்நுழைவு',
      question: 'OTP கிடைக்கவில்லை. என்ன செய்வது?',
      answer:
        'மீண்டும் அனுப்பு டைமர் முடியும் வரை காத்திருந்து Resend OTP அழுத்தவும். எண், நெட்வொர்க் மற்றும் SMS தடை அமைப்புகளைச் சரிபார்க்கவும். எண்ணை மாற்ற Change அழுத்தவும். தொடர்ந்தால் securestepsai@gmail.com-க்கு எழுதவும்.',
    },
    {
      id: 4,
      category: 'அறிவிப்புகள்',
      question: 'வருகை எச்சரிக்கைகள் ஏன் வரவில்லை?',
      answer:
        'கணினி அமைப்புகளில் EduForest Parent-க்கு அறிவிப்புகளை அனுமதிக்கவும். நிறுவனம் வருகையை பதிவு செய்ய வேண்டும்; சரியான பாதுகாவலர் எண் பதிவில் இருக்க வேண்டும். சிறந்த அனுபவத்திற்கு ஆன்லைனில் இருங்கள்.',
    },
    {
      id: 5,
      category: 'குரல்',
      question: 'குரல் அறிவிப்புகள் என்றால் என்ன?',
      answer:
        'சுயவிவரத்தில் இயக்கினால், முன்புறத்தில் புஷ் வரும்போது செயலி வருகை செய்தியை உரக்கப் படிக்கலாம். சுயவிவரத்தில் எப்போதும் முடக்கலாம்.',
    },
    {
      id: 6,
      category: 'வருகை',
      question: 'கடந்த வருகையை எங்கே பார்க்கலாம்?',
      answer:
        'வரலாறு மற்றும் சுருக்கத்திற்கு Attendance தாவலைத் திறக்கவும். நிறுவன அமைப்பின்படி Home-இல் சமீபத்திய சிறப்பம்சங்கள் தோன்றலாம்.',
    },
    {
      id: 7,
      category: 'தனியுரிமை',
      question: 'தனியுரிமைக் கொள்கை மற்றும் விதிமுறைகள் எங்கே?',
      answer:
        'சுயவிவரத்தைத் திறந்து, தனியுரிமைக் கொள்கை, விதிமுறைகள் அல்லது உதவி. https://eduforest.co.in இலும் படிக்கலாம்.',
    },
    {
      id: 8,
      category: 'ஆதரவு',
      question: 'தவறான வருகை அல்லது கணக்கு சிக்கலுக்கு யாரைத் தொடர்பு கொள்வது?',
      answer:
        'முதலில் உங்கள் நிறுவனத்தைத் தொடர்பு கொள்ளவும்—அவர்கள் பதிவுகளை நிர்வகிக்கிறார்கள். செயலி அல்லது உள்நுழைவுக்கு பதிவு செய்யப்பட்ட மொபைல் மற்றும் குறுகிய விவரத்துடன் securestepsai@gmail.com-க்கு எழுதவும்.',
    },
    {
      id: 9,
      category: 'அறிவிப்புகள் மற்றும் தனியுரிமை',
      question: 'புஷ் அறிவிப்புகளுக்கு எந்தத் தகவல் பயன்படுகிறது?',
      answer:
        'நிறுவனம் EduForest வழியாக வருகை புதுப்பிப்புகளை அனுப்புகிறது; எச்சரிக்கைகள் உங்கள் தொலைபேசியை அடைய எங்கள் சேவையகங்கள் உங்கள் பெற்றோர் கணக்குடன் இணைக்கப்பட்ட FCM சாதன டோக்கனைச் சேமிக்கலாம். செய்திகள் செயலியில் எச்சரிக்கை காட்ட பயன்படுகின்றன. முழு விவரம் செயலியிலுள்ள தனியுரிமைக் கொள்கையில்.',
    },
    {
      id: 10,
      category: 'அறிவிப்புகள் மற்றும் தனியுரிமை',
      question: 'குரல் அறிவிப்பு என் குரலை சேவையகத்திற்கு அனுப்புகிறதா?',
      answer:
        'இல்லை. செயலி செயலில் இருக்கும்போதும் சுயவிவரத்தில் அம்சம் இயக்கப்பட்டிருக்கும்போதும், குரல் அறிவிப்புகள் உங்கள் சாதனத்தின் உரை-குரல் மூலம் செய்தியை உள்ளூரில் படிக்கின்றன. EduForest-க்கு பதிவு அனுப்பப்படுவதில்லை.',
    },
  ],
};

export const getLocalizedParentHelpFaqs = (language: AppLanguage): LocalizedFaqItem[] => {
  return PARENT_HELP_FAQS[language] ?? PARENT_HELP_FAQS.en;
};

export const PRIVACY_PAGE: Record<AppLanguage, {
  headerTitle: string;
  headerSubtitle: string;
  introText: string;
  contactButton: string;
  sections: LocalizedSection[];
}> = {
  en: {
    headerTitle: 'Privacy Policy',
    headerSubtitle: 'Last Updated: April 4, 2026',
    introText: "Your privacy matters to EduForest. This policy explains what data we collect, how we use it, and what rights you have.",
    contactButton: 'Have questions? Email us',
    sections: [
      { title: '1. Introduction', icon: 'information-outline', content: 'EduForest respects your privacy and works to protect your personal data when you use our app and related services.' },
      { title: '2. The Data We Collect', icon: 'database-outline', content: 'We may collect identity data, contact data, student records, profile settings, technical device information, and service usage information needed to operate the app. For the Parent app, this may include a mobile push token (FCM) linked to your account so we can deliver attendance-related notifications you choose to receive.' },
      { title: '3. How We Use Your Data', icon: 'briefcase-check-outline', content: 'We use data to provide educational management features, maintain accounts, secure the service, comply with law, and improve product quality. For the Parent app, we also use your account and device token as needed to deliver attendance-related push notifications you have enabled on your device.' },
      { title: '4. Data Security', icon: 'shield-lock-outline', content: 'We use reasonable technical and organizational measures to reduce unauthorized access, misuse, alteration, or disclosure of personal data.' },
      { title: '5. Data Retention', icon: 'clock-time-three-outline', content: 'We keep data only as long as needed for service delivery, legal obligations, dispute handling, security, and operational continuity.' },
      { title: '6. Your Legal Rights', icon: 'scale-balance', content: 'Depending on applicable law, you may request access, correction, deletion, restriction, objection, portability, or withdrawal of consent for your personal data.' },
      { title: '7. Children\'s Privacy', icon: 'account-child-outline', content: 'Student information is managed by authorized institutions or educators. They are responsible for obtaining any required guardian consent before submitting student data.' },
      { title: '8. Data Deletion and Account Closure', icon: 'delete-outline', content: 'You may request account closure or data deletion by contacting support. Requests are processed subject to legal, compliance, and retention requirements.' },
      { title: '9. Push notifications and device messaging', icon: 'bell-ring-outline', content: 'The Parent app can deliver attendance-related alerts using push notifications (for example via Firebase Cloud Messaging). If you allow notifications on your device, your institute may send messages when attendance is updated. We may store a device push token linked to your parent account so the service can reach your device. Message payloads are used only to display alerts in the app; you can disable notifications in your device settings at any time.' },
      { title: '10. Voice announcements (optional)', icon: 'volume-high', content: 'You may turn on optional voice announcements in Profile so the app can read attendance messages aloud using your device’s built-in text-to-speech when you are using the app (for example when a notification arrives in the foreground). This uses on-device speech playback; we do not collect or store audio recordings of your voice for this feature. You can disable voice announcements at any time in Profile.' },
      { title: '11. Contact Us', icon: 'email-outline', content: 'For privacy questions or data requests, contact securestepsai@gmail.com. Office address: B-251, Sector 19, Noida, UP 201301, India.' },
    ],
  },
  hi: {
    headerTitle: 'प्राइवेसी पॉलिसी',
    headerSubtitle: 'अंतिम अपडेट: 4 अप्रैल 2026',
    introText: 'EduForest आपकी गोपनीयता को महत्व देता है। यह नीति बताती है कि हम कौन-सा डेटा एकत्र करते हैं, उसका उपयोग कैसे करते हैं, और आपके क्या अधिकार हैं।',
    contactButton: 'कोई सवाल है? हमें ईमेल करें',
    sections: [
      { title: '1. परिचय', icon: 'information-outline', content: 'EduForest आपकी गोपनीयता का सम्मान करता है और ऐप व संबंधित सेवाओं के उपयोग के दौरान आपके व्यक्तिगत डेटा की सुरक्षा के लिए प्रतिबद्ध है।' },
      { title: '2. हम कौन-सा डेटा एकत्र करते हैं', icon: 'database-outline', content: 'हम पहचान संबंधी डेटा, संपर्क विवरण, छात्र अभिलेख, प्रोफाइल सेटिंग्स, डिवाइस की तकनीकी जानकारी और सेवा उपयोग से जुड़ा डेटा एकत्र कर सकते हैं। पैरेंट ऐप के लिए इसमें आपके खाते से जुड़ा मोबाइल पुश टोकन (FCM) शामिल हो सकता है ताकि आप जो उपस्थिति संबंधी सूचनाएं प्राप्त करना चुनते हैं उन्हें भेजा जा सके।' },
      { title: '3. हम आपके डेटा का उपयोग कैसे करते हैं', icon: 'briefcase-check-outline', content: 'डेटा का उपयोग शैक्षणिक प्रबंधन सुविधाएं देने, खाता बनाए रखने, सेवा की सुरक्षा बनाए रखने, कानूनी अनुपालन और उत्पाद सुधार के लिए किया जाता है। पैरेंट ऐप के लिए, जब आप डिवाइस पर सूचनाएं सक्षम करते हैं तो उपस्थिति से जुड़ी पुश सूचनाएं भेजने हेतु आपके खाते और डिवाइस टोकन का उपयोग भी किया जा सकता है।' },
      { title: '4. डेटा सुरक्षा', icon: 'shield-lock-outline', content: 'अनधिकृत पहुंच, दुरुपयोग, बदलाव या खुलासे के जोखिम को कम करने के लिए हम उचित तकनीकी और संगठनात्मक उपाय अपनाते हैं।' },
      { title: '5. डेटा संरक्षण अवधि', icon: 'clock-time-three-outline', content: 'हम डेटा उतनी ही अवधि तक रखते हैं जितनी सेवा प्रदान करने, कानूनी दायित्वों, विवाद निपटान, सुरक्षा और संचालन की निरंतरता के लिए आवश्यक हो।' },
      { title: '6. आपके कानूनी अधिकार', icon: 'scale-balance', content: 'लागू कानून के अनुसार आप अपने व्यक्तिगत डेटा तक पहुंच, संशोधन, हटाने, प्रतिबंध, आपत्ति, पोर्टेबिलिटी या सहमति वापस लेने का अनुरोध कर सकते हैं।' },
      { title: '7. बच्चों की गोपनीयता', icon: 'account-child-outline', content: 'छात्र संबंधी जानकारी अधिकृत संस्थानों या शिक्षकों द्वारा प्रबंधित की जाती है। छात्र डेटा जमा करने से पहले आवश्यक अभिभावक सहमति लेना उनकी जिम्मेदारी है।' },
      { title: '8. डेटा हटाना और अकाउंट बंद करना', icon: 'delete-outline', content: 'आप सपोर्ट से संपर्क करके अकाउंट बंद करने या डेटा हटाने का अनुरोध कर सकते हैं। अनुरोधों को कानूनी और अनुपालन नियमों के अनुसार संसाधित किया जाएगा।' },
      { title: '9. पुश सूचनाएं और डिवाइस मैसेजिंग', icon: 'bell-ring-outline', content: 'पैरेंट ऐप उपस्थिति से जुड़े अलर्ट पुश सूचनाओं (जैसे Firebase Cloud Messaging) के जरिए भेज सकता है। यदि आप डिवाइस पर सूचनाएं अनुमति देते हैं, तो आपका संस्थान उपस्थिति अपडेट होने पर संदेश भेज सकता है। हम आपके पैरेंट खाते से जुड़ा डिवाइस पुश टोकन संग्रहीत कर सकते हैं ताकि सेवा आपके डिवाइस तक पहुंच सके। संदेश ऐप में अलर्ट दिखाने के लिए उपयोग होते हैं; आप कभी भी डिवाइस सेटिंग्स में सूचनाएं बंद कर सकते हैं।' },
      { title: '10. वॉइस घोषणाएं (वैकल्पिक)', icon: 'volume-high', content: 'प्रोफाइल में वैकल्पिक वॉइस घोषणाएं चालू करने पर ऐप आपके डिवाइस के अंतर्निहित टेक्स्ट-टू-स्पीच का उपयोग करके उपस्थिति संदेशों को जोर से पढ़ सकता है (उदाहरण जब अग्रभूमि में सूचना आती है)। यह ऑन-डिवाइस प्लेबैक है; हम इस सुविधा के लिए आपकी आवाज़ की रिकॉर्डिंग एकत्र या संग्रहीत नहीं करते। आप प्रोफाइल से कभी भी वॉइस घोषणाएं बंद कर सकते हैं।' },
      { title: '11. संपर्क करें', icon: 'email-outline', content: 'गोपनीयता या डेटा संबंधी अनुरोधों के लिए securestepsai@gmail.com पर संपर्क करें। कार्यालय का पता: बी-251, सेक्टर 19, नोएडा, यूपी 201301, भारत।' },
    ],
  },
  bn: {
    headerTitle: 'প্রাইভেসি পলিসি',
    headerSubtitle: 'সর্বশেষ আপডেট: ৪ এপ্রিল ২০২৬',
    introText: 'EduForest আপনার গোপনীয়তাকে গুরুত্ব দেয়। এই নীতিতে আমরা কোন তথ্য সংগ্রহ করি, কীভাবে ব্যবহার করি, এবং আপনার কী অধিকার আছে তা ব্যাখ্যা করা হয়েছে।',
    contactButton: 'প্রশ্ন আছে? আমাদের ইমেল করুন',
    sections: [
      { title: '1. পরিচিতি', icon: 'information-outline', content: 'EduForest আপনার গোপনীয়তাকে সম্মান করে এবং অ্যাপ ও সংশ্লিষ্ট পরিষেবা ব্যবহারের সময় আপনার ব্যক্তিগত তথ্য সুরক্ষিত রাখতে সচেষ্ট।' },
      { title: '2. আমরা কোন তথ্য সংগ্রহ করি', icon: 'database-outline', content: 'আমরা পরিচয়সংক্রান্ত তথ্য, যোগাযোগের তথ্য, শিক্ষার্থীর রেকর্ড, প্রোফাইল সেটিংস, ডিভাইসের প্রযুক্তিগত তথ্য এবং পরিষেবা ব্যবহারের তথ্য সংগ্রহ করতে পারি। প্যারেন্ট অ্যাপের জন্য এর মধ্যে আপনার অ্যাকাউন্টের সাথে যুক্ত মোবাইল পুশ টোকেন (FCM) থাকতে পারে যাতে আপনি যে উপস্থিতি-সম্পর্কিত বিজ্ঞপ্তি পেতে চান সেগুলো পাঠানো যায়।' },
      { title: '3. আপনার তথ্য কীভাবে ব্যবহার করি', icon: 'briefcase-check-outline', content: 'এই তথ্য শিক্ষাপ্রশাসন সম্পর্কিত সুবিধা দেওয়া, অ্যাকাউন্ট রক্ষণাবেক্ষণ, পরিষেবার নিরাপত্তা, আইনি সম্মতি এবং পণ্যের উন্নতির জন্য ব্যবহার করা হয়। প্যারেন্ট অ্যাপের জন্য, ডিভাইসে বিজ্ঞপ্তি চালু থাকলে উপস্থিতি-সম্পর্কিত পুশ বিজ্ঞপ্তি পাঠাতে আপনার অ্যাকাউন্ট ও ডিভাইস টোকেনও প্রয়োজনীয় মতো ব্যবহার করা হতে পারে।' },
      { title: '4. তথ্যের নিরাপত্তা', icon: 'shield-lock-outline', content: 'অননুমোদিত প্রবেশ, অপব্যবহার, পরিবর্তন বা প্রকাশের ঝুঁকি কমাতে আমরা যুক্তিসঙ্গত প্রযুক্তিগত ও সাংগঠনিক ব্যবস্থা গ্রহণ করি।' },
      { title: '5. তথ্য সংরক্ষণের মেয়াদ', icon: 'clock-time-three-outline', content: 'পরিষেবা প্রদান, আইনি বাধ্যবাধকতা, বিরোধ নিষ্পত্তি, নিরাপত্তা এবং পরিচালনাগত ধারাবাহিকতার জন্য যতদিন প্রয়োজন ততদিন তথ্য সংরক্ষণ করা হয়।' },
      { title: '6. আপনার আইনি অধিকার', icon: 'scale-balance', content: 'প্রযোজ্য আইন অনুযায়ী আপনি আপনার ব্যক্তিগত তথ্য অ্যাক্সেস, সংশোধন, মুছে ফেলা, সীমাবদ্ধ করা, আপত্তি, স্থানান্তরযোগ্যতা বা সম্মতি প্রত্যাহারের অনুরোধ করতে পারেন।' },
      { title: '7. শিশুদের গোপনীয়তা', icon: 'account-child-outline', content: 'শিক্ষার্থীর তথ্য অনুমোদিত প্রতিষ্ঠান বা শিক্ষকেরা পরিচালনা করেন। শিক্ষার্থীর তথ্য জমা দেওয়ার আগে প্রয়োজনীয় অভিভাবক সম্মতি নেওয়া তাদের দায়িত্ব।' },
      { title: '8. তথ্য মুছে ফেলা ও অ্যাকাউন্ট বন্ধ', icon: 'delete-outline', content: 'সাপোর্টে যোগাযোগ করে আপনি অ্যাকাউন্ট বন্ধ বা তথ্য মুছে ফেলার অনুরোধ করতে পারেন। অনুরোধগুলি আইনি ও কমপ্লায়েন্স নিয়ম অনুযায়ী প্রক্রিয়াকরণ করা হবে।' },
      { title: '9. পুশ বিজ্ঞপ্তি ও ডিভাইস মেসেজিং', icon: 'bell-ring-outline', content: 'প্যারেন্ট অ্যাপ উপস্থিতি-সম্পর্কিত সতর্কতা পুশ বিজ্ঞপ্তির মাধ্যমে পাঠাতে পারে (যেমন Firebase Cloud Messaging)। আপনি ডিভাইসে বিজ্ঞপ্তির অনুমতি দিলে আপনার প্রতিষ্ঠান উপস্থিতি আপডেট হলে বার্তা পাঠাতে পারে। আমরা আপনার প্যারেন্ট অ্যাকাউন্টের সাথে যুক্ত ডিভাইস পুশ টোকেন সংরক্ষণ করতে পারি যাতে সেবা আপনার ডিভাইসে পৌঁছাতে পারে। বার্তাগুলো অ্যাপে সতর্কতা দেখানোর জন্য ব্যবহৃত হয়; আপনি যেকোনো সময় ডিভাইস সেটিংসে বিজ্ঞপ্তি বন্ধ করতে পারেন।' },
      { title: '10. ভয়েস ঘোষণা (ঐচ্ছিক)', icon: 'volume-high', content: 'প্রোফাইলে ঐচ্ছিক ভয়েস ঘোষণা চালু করলে অ্যাপ আপনার ডিভাইসের অন্তর্নির্মিত টেক্সট-টু-স্পিচ ব্যবহার করে উপস্থিতি বার্তা জোরে পড়তে পারে (যেমন অ্যাপটি অগ্রভাগে থাকাকালীন বিজ্ঞপ্তি এলে)। এটি ডিভাইসে প্লেব্যাক; এই বৈশিষ্ট্যের জন্য আমরা আপনার কণ্ঠের রেকর্ড সংগ্রহ বা সংরক্ষণ করি না। আপনি যেকোনো সময় প্রোফাইল থেকে ভয়েস ঘোষণা বন্ধ করতে পারেন।' },
      { title: '11. যোগাযোগ করুন', icon: 'email-outline', content: 'গোপনীয়তা বা তথ্যসংক্রান্ত অনুরোধের জন্য securestepsai@gmail.com-এ যোগাযোগ করুন। অফিসের ঠিকানা: বি-251, সেক্টর 19, নয়ডা, ইউপি 201301, ভারত।' },
    ],
  },
  ta: {
    headerTitle: 'தனியுரிமைக் கொள்கை',
    headerSubtitle: 'கடைசியாக புதுப்பிக்கப்பட்டது: 4 ஏப்ரல் 2026',
    introText: 'EduForest உங்கள் தனியுரிமையை மதிக்கிறது. இந்த கொள்கையில் எவ்வகையான தகவல்கள் சேகரிக்கப்படுகின்றன, அவை எவ்வாறு பயன்படுத்தப்படுகின்றன, மேலும் உங்களுக்கு உள்ள உரிமைகள் என்ன என்பதைக் கூறுகிறது.',
    contactButton: 'கேள்விகள் உள்ளனவா? எங்களுக்கு மின்னஞ்சல் செய்யவும்',
    sections: [
      { title: '1. அறிமுகம்', icon: 'information-outline', content: 'EduForest உங்கள் தனியுரிமையை மதிக்கிறது; பயன்பாடு மற்றும் தொடர்புடைய சேவைகளை பயன்படுத்தும் போது உங்கள் தனிப்பட்ட தகவலை பாதுகாக்க முயற்சிக்கிறது.' },
      { title: '2. எங்கள் தகவல் சேகரிப்பு', icon: 'database-outline', content: 'அடையாளத் தகவல், தொடர்பு விவரங்கள், மாணவர் பதிவுகள், சுயவிவர அமைப்புகள், சாதனத்தின் தொழில்நுட்ப தகவல் மற்றும் சேவை பயன்பாட்டு விவரங்கள் போன்றவை சேகரிக்கப்படலாம். பெற்றோர் செயலிக்கு, நீங்கள் பெற விரும்பும் வருகை தொடர்பான அறிவிப்புகளை அனுப்ப உங்கள் கணக்குடன் இணைக்கப்பட்ட மொபைல் புஷ் டோக்கன் (FCM) அடங்கலாம்.' },
      { title: '3. உங்கள் தகவல் எவ்வாறு பயன்படுத்தப்படுகிறது', icon: 'briefcase-check-outline', content: 'இந்த தகவல் கல்வி நிர்வாக வசதிகள் வழங்க, கணக்கை பராமரிக்க, சேவையின் பாதுகாப்பை உறுதி செய்ய, சட்ட பின்பற்றலை மேற்கொள்ள மற்றும் தயாரிப்பை மேம்படுத்த பயன்படுத்தப்படுகிறது. பெற்றோர் செயலிக்கு, சாதனத்தில் அறிவிப்புகளை இயக்கியிருக்கும்போது வருகை தொடர்பான புஷ் அறிவிப்புகளை அனுப்ப உங்கள் கணக்கு மற்றும் சாதன டோக்கனும் தேவைப்படுமாறு பயன்படுத்தப்படலாம்.' },
      { title: '4. தகவல் பாதுகாப்பு', icon: 'shield-lock-outline', content: 'அனுமதியற்ற அணுகல், தவறான பயன்பாடு, மாற்றம் அல்லது வெளியீட்டை குறைக்க நியாயமான தொழில்நுட்ப மற்றும் அமைப்புசார்ந்த நடவடிக்கைகள் எடுக்கப்படுகின்றன.' },
      { title: '5. தகவல் பாதுகாப்பு காலம்', icon: 'clock-time-three-outline', content: 'சேவை வழங்கல், சட்டப் பொறுப்புகள், பிரச்சினை தீர்வு, பாதுகாப்பு மற்றும் செயல்பாட்டு தொடர்ச்சிக்கு தேவையான அளவு காலம் தகவல் வைத்திருக்கப்படுகிறது.' },
      { title: '6. உங்கள் சட்ட உரிமைகள்', icon: 'scale-balance', content: 'பொருந்தும் சட்டத்தின்படி உங்கள் தனிப்பட்ட தகவலை அணுக, திருத்த, நீக்க, கட்டுப்படுத்த, எதிர்ப்பு தெரிவிக்க, மாற்றிக்கொள்ள அல்லது ஒப்புதலை திரும்பப் பெற கோரலாம்.' },
      { title: '7. குழந்தைகளின் தனியுரிமை', icon: 'account-child-outline', content: 'மாணவர் தகவல்கள் அங்கீகரிக்கப்பட்ட நிறுவனம் அல்லது ஆசிரியர்களால் நிர்வகிக்கப்படுகின்றன. மாணவர் தகவலை சமர்ப்பிப்பதற்கு முன் தேவையான பாதுகாவலர் ஒப்புதலை பெறுவது அவர்களின் பொறுப்பு.' },
      { title: '8. தகவல் நீக்கம் மற்றும் கணக்கு மூடல்', icon: 'delete-outline', content: 'ஆதரவுத் அணியை தொடர்பு கொண்டு கணக்கை மூடவோ தகவலை நீக்கவோ கோரலாம். கோரிக்கைகள் சட்ட மற்றும் இணக்கப்பாட்டு விதிகளின்படி செயலாக்கப்படும்.' },
      { title: '9. புஷ் அறிவிப்புகள் மற்றும் சாதன செய்தியனுப்பு', icon: 'bell-ring-outline', content: 'பெற்றோர் செயலி வருகை தொடர்பான எச்சரிக்கைகளை புஷ் அறிவிப்புகள் வழியாக அனுப்பலாம் (எ.கா. Firebase Cloud Messaging). சாதனத்தில் அறிவிப்புகளை அனுமதித்தால், வருகை புதுப்பிக்கப்படும்போது உங்கள் நிறுவனம் செய்திகளை அனுப்பலாம். சேவை உங்கள் சாதனத்தை அடைய உங்கள் பெற்றோர் கணக்குடன் இணைக்கப்பட்ட புஷ் டோக்கனை நாங்கள் சேமிக்கலாம். செய்திகள் செயலியில் எச்சரிக்கைகளை காட்ட பயன்படுகின்றன; சாதன அமைப்புகளில் எப்போதும் அறிவிப்புகளை முடக்கலாம்.' },
      { title: '10. குரல் அறிவிப்புகள் (விருப்பம்)', icon: 'volume-high', content: 'சுயவிவரத்தில் விருப்ப குரல் அறிவிப்புகளை இயக்கினால், செயலி முன்புறத்தில் இருக்கும்போது (எ.கா. அறிவிப்பு வரும்போது) உங்கள் சாதனத்தின் உள்ளமைக்கப்பட்ட உரை-குரல் மூலம் வருகை செய்திகளை உரக்க படிக்கலாம். இது சாதனத்திலேயே இயக்கம்; இந்த வசதிக்கு உங்கள் குரல் பதிவுகளை நாங்கள் சேகரிக்கவோ சேமிக்கவோ மாட்டோம். சுயவிவரத்தில் எப்போதும் குரல் அறிவிப்புகளை முடக்கலாம்.' },
      { title: '11. எங்களை தொடர்பு கொள்ளவும்', icon: 'email-outline', content: 'தனியுரிமை அல்லது தகவல் தொடர்பான கோரிக்கைகளுக்கு securestepsai@gmail.com-ஐ தொடர்பு கொள்ளவும். அலுவலக முகவரி: பி-251, செக்டர் 19, நொய்டா, யுபி 201301, இந்தியா.' },
    ],
  },
};

export const TERMS_PAGE: Record<AppLanguage, {
  headerTitle: string;
  headerSubtitle: string;
  introText: string;
  contactButton: string;
  sections: LocalizedSection[];
}> = {
  en: {
    headerTitle: 'Terms & Conditions',
    headerSubtitle: 'Last Updated: April 4, 2026',
    introText: 'Please read these terms carefully before using EduForest.',
    contactButton: 'Have questions? Email us',
    sections: [
      { title: '1. Agreement to Terms', icon: 'handshake-outline', content: 'By accessing or using EduForest, you agree to follow these terms and any related policies referenced in the service.' },
      { title: '2. Intellectual Property Rights', icon: 'copyright', content: 'The application, branding, software, and related content remain the property of EduForest or its licensors unless otherwise stated.' },
      { title: '3. User Representations', icon: 'account-check-outline', content: 'You confirm that information you provide is accurate, current, lawful, and that you have authority to use the service for your institution or organization.' },
      { title: '4. Prohibited Activities', icon: 'alert-circle-outline', content: 'You must not misuse the service, send spam, abuse student data, attempt fraud, or violate applicable laws and acceptable use requirements.' },
      { title: '5. User Content and Submitted Information', icon: 'license', content: 'You remain responsible for the content and records you submit. You grant EduForest a limited right to process and store that information to operate and support the service.' },
      { title: '6. Mobile Application License', icon: 'cellphone-link', content: 'We grant a limited, revocable, non-transferable license to use the app on devices you own or control, subject to these terms.' },
      { title: '7. Student Data and Educational Records', icon: 'school-outline', content: 'You are responsible for having authority to collect and manage student information and for complying with applicable data protection obligations.' },
      { title: '8. Limitation of Liability', icon: 'gavel', content: 'EduForest is not responsible for indirect losses, outages, or issues beyond reasonable operational control.' },
      { title: '9. Termination', icon: 'account-remove-outline', content: 'We may suspend or terminate access for misuse, harmful conduct, policy violations, or other justified reasons. You may also request closure of your account.' },
      { title: '10. Notifications and voice (Parent app)', icon: 'bell-ring-outline', content: 'If you use the EduForest Parent app, you may receive push notifications about your child’s attendance when your device allows it and when your institute sends updates. Optional voice announcements use your device’s text-to-speech to read messages aloud while you use the app; you control this in Profile. You may withdraw notification consent in your device settings; voice can be turned off in the app at any time.' },
      { title: '11. Contact Us', icon: 'email-outline', content: 'For complaints or clarification, contact securestepsai@gmail.com. Office address: B-251, Sector 19, Noida, UP 201301, India.' },
    ],
  },
  hi: {
    headerTitle: 'नियम और शर्तें',
    headerSubtitle: 'अंतिम अपडेट: 4 अप्रैल 2026',
    introText: 'EduForest का उपयोग करने से पहले कृपया इन नियमों को ध्यान से पढ़ें।',
    contactButton: 'कोई सवाल है? हमें ईमेल करें',
    sections: [
      { title: '1. शर्तों की स्वीकृति', icon: 'handshake-outline', content: 'EduForest का उपयोग करके आप इन नियमों और सेवा से संबंधित नीतियों का पालन करने के लिए सहमत होते हैं।' },
      { title: '2. बौद्धिक संपदा अधिकार', icon: 'copyright', content: 'ऐप, ब्रांडिंग, सॉफ्टवेयर और संबंधित सामग्री, जब तक अलग से न कहा जाए, EduForest या उसके लाइसेंसधारकों की संपत्ति हैं।' },
      { title: '3. उपयोगकर्ता के आश्वासन', icon: 'account-check-outline', content: 'आप पुष्टि करते हैं कि दी गई जानकारी सही, वर्तमान और वैध है, तथा आप अपनी संस्था या संगठन की ओर से सेवा उपयोग करने के अधिकृत हैं।' },
      { title: '4. निषिद्ध गतिविधियाँ', icon: 'alert-circle-outline', content: 'सेवा का दुरुपयोग, स्पैम भेजना, छात्र डेटा का गलत उपयोग, धोखाधड़ी, अथवा लागू कानूनों और स्वीकृत उपयोग मानकों का उल्लंघन प्रतिबंधित है।' },
      { title: '5. उपयोगकर्ता सामग्री और जमा की गई जानकारी', icon: 'license', content: 'आपके द्वारा जमा की गई सामग्री और अभिलेखों के लिए आप स्वयं जिम्मेदार रहते हैं। सेवा चलाने और सहायता देने के लिए EduForest को सीमित रूप से जानकारी संसाधित और संग्रहीत करने का अधिकार मिलता है।' },
      { title: '6. मोबाइल ऐप लाइसेंस', icon: 'cellphone-link', content: 'हम आपको इन नियमों के अधीन आपके नियंत्रण वाले उपकरणों पर ऐप उपयोग करने का सीमित, वापस लिया जा सकने वाला लाइसेंस देते हैं।' },
      { title: '7. छात्र डेटा और शैक्षणिक अभिलेख', icon: 'school-outline', content: 'छात्र जानकारी एकत्र और प्रबंधित करने का उचित अधिकार होना तथा डेटा सुरक्षा से जुड़ी जिम्मेदारियों का पालन करना आपकी जिम्मेदारी है।' },
      { title: '8. दायित्व की सीमा', icon: 'gavel', content: 'अप्रत्यक्ष हानि, सेवा बाधा या हमारे उचित नियंत्रण से बाहर की समस्याओं के लिए EduForest जिम्मेदार नहीं होगा।' },
      { title: '9. समाप्ति', icon: 'account-remove-outline', content: 'दुरुपयोग, हानिकारक आचरण, नीति उल्लंघन या अन्य उचित कारणों पर पहुंच निलंबित या समाप्त की जा सकती है। आप अकाउंट बंद करने का अनुरोध भी कर सकते हैं।' },
      { title: '10. सूचनाएं और वॉइस (पैरेंट ऐप)', icon: 'bell-ring-outline', content: 'यदि आप EduForest पैरेंट ऐप का उपयोग करते हैं, तो जब आपका डिवाइस अनुमति देता है और आपका संस्थान अपडेट भेजता है, तो आपको अपने बच्चे की उपस्थिति के बारे में पुश सूचनाएं मिल सकती हैं। वैकल्पिक वॉइस घोषणाएं ऐप उपयोग के दौरान संदेशों को जोर से पढ़ने के लिए आपके डिवाइस के टेक्स्ट-टू-स्पीच का उपयोग करती हैं; इसे प्रोफाइल में नियंत्रित किया जाता है। आप डिवाइस सेटिंग्स में सूचना सहमति वापस ले सकते हैं; वॉइस को कभी भी ऐप में बंद किया जा सकता है।' },
      { title: '11. संपर्क करें', icon: 'email-outline', content: 'शिकायत या जानकारी के लिए securestepsai@gmail.com पर संपर्क करें। कार्यालय का पता: बी-251, सेक्टर 19, नोएडা, यूपी 201301, भारत।' },
    ],
  },
  bn: {
    headerTitle: 'শর্তাবলী',
    headerSubtitle: 'সর্বশেষ আপডেট: ৪ এপ্রিল ২০২৬',
    introText: 'EduForest ব্যবহার করার আগে অনুগ্রহ করে এই শর্তাবলী মনোযোগ দিয়ে পড়ুন।',
    contactButton: 'প্রশ্ন আছে? আমাদের ইমেল করুন',
    sections: [
      { title: '1. শর্তে সম্মতি', icon: 'handshake-outline', content: 'EduForest ব্যবহার করলে আপনি এই শর্তাবলী এবং পরিষেবার সাথে সম্পর্কিত নীতিগুলি মেনে চলতে সম্মত হন।' },
      { title: '2. মেধাস্বত্ব অধিকার', icon: 'copyright', content: 'অ্যাপ, ব্র্যান্ডিং, সফটওয়্যার এবং সংশ্লিষ্ট কনটেন্ট, যদি আলাদা করে উল্লেখ না থাকে, EduForest বা তার লাইসেন্সদাতাদের সম্পত্তি।' },
      { title: '3. ব্যবহারকারীর নিশ্চয়তা', icon: 'account-check-outline', content: 'আপনি নিশ্চিত করেন যে আপনার দেওয়া তথ্য সঠিক, বর্তমান এবং আইনসম্মত, এবং আপনি আপনার প্রতিষ্ঠান বা সংস্থার পক্ষে পরিষেবাটি ব্যবহার করার অধিকার রাখেন।' },
      { title: '4. নিষিদ্ধ কার্যকলাপ', icon: 'alert-circle-outline', content: 'পরিষেবার অপব্যবহার, স্প্যাম পাঠানো, শিক্ষার্থীর তথ্যের অপব্যবহার, প্রতারণা, অথবা প্রযোজ্য আইন বা গ্রহণযোগ্য ব্যবহারের শর্ত ভঙ্গ করা নিষিদ্ধ।' },
      { title: '5. ব্যবহারকারীর কনটেন্ট এবং জমা দেওয়া তথ্য', icon: 'license', content: 'আপনি জমা দেওয়া কনটেন্ট এবং রেকর্ডের জন্য দায়ী থাকবেন। পরিষেবা চালানো ও সহায়তা দেওয়ার জন্য EduForest-কে সীমিতভাবে তথ্য প্রক্রিয়াকরণ ও সংরক্ষণের অধিকার দেওয়া হয়।' },
      { title: '6. মোবাইল অ্যাপ লাইসেন্স', icon: 'cellphone-link', content: 'এই শর্তাবলীর অধীনে আপনার নিয়ন্ত্রণাধীন ডিভাইসে অ্যাপ ব্যবহারের জন্য আমরা সীমিত ও প্রত্যাহারযোগ্য লাইসেন্স প্রদান করি।' },
      { title: '7. শিক্ষার্থীর তথ্য ও শিক্ষাবিষয়ক রেকর্ড', icon: 'school-outline', content: 'শিক্ষার্থীর তথ্য সংগ্রহ ও পরিচালনার যথাযথ অধিকার থাকা এবং তথ্য সুরক্ষা-সংক্রান্ত দায়িত্ব পালন করা আপনার দায়িত্ব।' },
      { title: '8. দায়বদ্ধতার সীমা', icon: 'gavel', content: 'পরোক্ষ ক্ষতি, পরিষেবা বিঘ্ন বা আমাদের যুক্তিসঙ্গত নিয়ন্ত্রণের বাইরে থাকা সমস্যার জন্য EduForest দায়ী নয়।' },
      { title: '9. সমাপ্তি', icon: 'account-remove-outline', content: 'অপব্যবহার, ক্ষতিকর আচরণ, নীতি লঙ্ঘন বা অন্য যৌক্তিক কারণে অ্যাক্সেস স্থগিত বা বন্ধ করা হতে পারে। আপনি অ্যাকাউন্ট বন্ধ করার অনুরোধও করতে পারেন।' },
      { title: '10. বিজ্ঞপ্তি ও ভয়েস (প্যারেন্ট অ্যাপ)', icon: 'bell-ring-outline', content: 'আপনি EduForest প্যারেন্ট অ্যাপ ব্যবহার করলে, ডিভাইস অনুমতি দিলে এবং প্রতিষ্ঠান আপডেট পাঠালে আপনার সন্তানের উপস্থিতি সম্পর্কে পুশ বিজ্ঞপ্তি পেতে পারেন। ঐচ্ছিক ভয়েস ঘোষণা অ্যাপ ব্যবহারের সময় বার্তা জোরে পড়তে ডিভাইসের টেক্সট-টু-স্পিচ ব্যবহার করে; এটি প্রোফাইলে নিয়ন্ত্রিত হয়। ডিভাইস সেটিংসে বিজ্ঞপ্তি সম্মতি প্রত্যাহার করতে পারেন; ভয়েস যেকোনো সময় অ্যাপে বন্ধ করা যায়।' },
      { title: '11. যোগাযোগ করুন', icon: 'email-outline', content: 'অভিযোগ বা তথ্যের জন্য securestepsai@gmail.com-এ যোগাযোগ করুন। অফিসের ঠিকানা: বি-251, সেক্টর 19, নয়ডা, ইউপি 201301, ভারত।' },
    ],
  },
  ta: {
    headerTitle: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    headerSubtitle: 'கடைசியாக புதுப்பிக்கப்பட்டது: 4 ஏப்ரல் 2026',
    introText: 'EduForest-ஐ பயன்படுத்துவதற்கு முன் இந்த விதிமுறைகளை கவனமாக வாசிக்கவும்.',
    contactButton: 'கேள்விகள் உள்ளனவா? எங்களுக்கு மின்னஞ்சல் செய்யவும்',
    sections: [
      { title: '1. விதிமுறைகளுக்கு ஒப்புதல்', icon: 'handshake-outline', content: 'EduForest-ஐ பயன்படுத்துவதன் மூலம் இந்த விதிமுறைகள் மற்றும் சேவையுடன் தொடர்புடைய கொள்கைகளை நீங்கள் ஏற்கிறீர்கள்.' },
      { title: '2. அறிவுசார் சொத்து உரிமைகள்', icon: 'copyright', content: 'ஆப், பிராண்டிங், மென்பொருள் மற்றும் தொடர்புடைய உள்ளடக்கம், வேறு விதமாக குறிப்பிடப்படாவிட்டால், EduForest அல்லது அதன் உரிமம் வழங்குநர்களின் சொத்தாகும்.' },
      { title: '3. பயனர் உறுதிப்பாடுகள்', icon: 'account-check-outline', content: 'நீங்கள் வழங்கும் தகவல் சரியானது, தற்போதையது, சட்டபூர்வமானது என்றும், உங்கள் நிறுவனம் அல்லது அமைப்பின் சார்பில் சேவையை பயன்படுத்த உங்களுக்கு அதிகாரம் உண்டு என்றும் உறுதிப்படுத்துகிறீர்கள்.' },
      { title: '4. தடை செய்யப்பட்ட செயல்பாடுகள்', icon: 'alert-circle-outline', content: 'சேவையின் தவறான பயன்பாடு, ஸ்பாம் அனுப்புதல், மாணவர் தகவலை தவறாக பயன்படுத்துதல், மோசடி, அல்லது பொருந்தும் சட்டங்கள் மற்றும் ஏற்றுக்கொள்ளத்தக்க பயன்பாட்டு விதிகளை மீறுதல் தடைசெய்யப்பட்டுள்ளது.' },
      { title: '5. பயனர் உள்ளடக்கம் மற்றும் சமர்ப்பிக்கப்பட்ட தகவல்', icon: 'license', content: 'நீங்கள் சமர்ப்பிக்கும் உள்ளடக்கம் மற்றும் பதிவுகளுக்கு நீங்கள் பொறுப்பாக இருப்பீர்கள். சேவையை இயக்கவும் ஆதரிக்கவும் EduForest-க்கு வரையறுக்கப்பட்ட தகவல் செயலாக்கம் மற்றும் சேமிப்பு உரிமை வழங்கப்படுகிறது.' },
      { title: '6. மொபைல் ஆப் உரிமம்', icon: 'cellphone-link', content: 'இந்த விதிமுறைகளின் கீழ், உங்கள் கட்டுப்பாட்டில் உள்ள சாதனங்களில் ஆப்பைப் பயன்படுத்த ஒரு வரையறுக்கப்பட்ட மற்றும் திரும்பப்பெறக்கூடிய உரிமம் வழங்கப்படுகிறது.' },
      { title: '7. மாணவர் தகவல் மற்றும் கல்வி பதிவுகள்', icon: 'school-outline', content: 'மாணவர் தகவலை சேகரித்து நிர்வகிக்கும் உரிய அதிகாரமும், தகவல் பாதுகாப்பு கடமைகளை பின்பற்றுவதும் உங்கள் பொறுப்பாகும்.' },
      { title: '8. பொறுப்பின் வரம்பு', icon: 'gavel', content: 'மறைமுக இழப்புகள், சேவை தடைகள் அல்லது எங்கள் நியாயமான கட்டுப்பாட்டிற்கு அப்பாற்பட்ட பிரச்சினைகளுக்கு EduForest பொறுப்பல்ல.' },
      { title: '9. நிறுத்தல்', icon: 'account-remove-outline', content: 'தவறான பயன்பாடு, தீங்கான நடத்தை, கொள்கை மீறல் அல்லது வேறு நியாயமான காரணங்களுக்காக அணுகலை இடைநிறுத்தவோ நிறுத்தவோ முடியும். கணக்கை மூடுவதற்கும் நீங்கள் கோரலாம்.' },
      { title: '10. அறிவிப்புகள் மற்றும் குரல் (பெற்றோர் செயலி)', icon: 'bell-ring-outline', content: 'EduForest பெற்றோர் செயலியைப் பயன்படுத்தும்போது, சாதனம் அனுமதித்தாலும் உங்கள் நிறுவனம் புதுப்பிப்புகளை அனுப்பும்போதும் உங்கள் குழந்தையின் வருகை தொடர்பான புஷ் அறிவிப்புகளைப் பெறலாம். விருப்ப குரல் அறிவிப்புகள் செயலியைப் பயன்படுத்தும்போது செய்திகளை உரக்கப் படிக்க சாதனத்தின் உரை-குரலைப் பயன்படுகின்றன; இது சுயவிவரத்தில் கட்டுப்படுத்தப்படுகிறது. சாதன அமைப்புகளில் அறிவிப்பு ஒப்புதலைத் திரும்பப் பெறலாம்; குரலை எப்போதும் செயலியில் முடக்கலாம்.' },
      { title: '11. எங்களை தொடர்பு கொள்ளவும்', icon: 'email-outline', content: 'புகார்கள் அல்லது விளக்கங்களுக்கு securestepsai@gmail.com-ஐ தொடர்பு கொள்ளவும். அலுவலக முகவரி: பி-251, செக்டர் 19, நொய்டா, யுபி 201301, இந்தியா.' },
    ],
  },
};